### PR TITLE
i#4847 AArch64 v8.0 memory decode: Add more ST1 decode tests

### PR DESCRIPTION
**Pull request by MDevereau**
Add a wider and more extensive range of decoder tests for ST1.

Issue: #4847, #2626

### CODE REVIEW

**Review by AssadHashmi — CHANGES_REQUESTED** [review]
Please line up the colon delimiters between fields. This is to ensure ease of machine readability/parsing for future test use-cases. 

Ideally we should align the entire file but aligning by group is fine if that's too time-consuming.

**Comment by MDevereau** [comment]
> 
> 
> Please line up the colon delimiters between fields. This is to ensure ease of machine readability/parsing for future test use-cases.
> 
> Ideally we should align the entire file but aligning by group is fine if that's too time-consuming.

Done

**Review by AssadHashmi — APPROVED** [review]

**Comment by drbot0** [comment]
Test message from new Jenkins CI.

**Comment by drbot0** [comment]
Test message from old Jenkins CI.

**Pull request merged**
