### PR TITLE
Add missing system registers for AArch64

### PR DESCRIPTION
**Pull request by yury-khrustalev**
#1569 Add decoding and encoding for system registers TPIDRRO_EL0 and CNTVCT_EL0.

### CODE REVIEW

**Comment by derekbruening** [comment]
The code change looks good at a high level to me: @AssadHashmi if you could look at the arch details.
(Commit message missing `Issue: `; title missing issue #; will be fixed on merge.)

**Comment by yury-khrustalev** [comment]
@derekbruening, why this build fails: https://travis-ci.com/github/DynamoRIO/dynamorio/jobs/356381232 ? It looks like it is interrupted.

**Comment by derekbruening** [comment]
> @derekbruening, why this build fails: https://travis-ci.com/github/DynamoRIO/dynamorio/jobs/356381232 ? It looks like it is interrupted.

Travis Mac VM bug: #4223.  Trying to find a workaround: #4345

**Comment by abhinav92003** [comment]
> > @derekbruening, why this build fails: https://travis-ci.com/github/DynamoRIO/dynamorio/jobs/356381232 ? It looks like it is interrupted.
> 
> Travis Mac VM bug: #4223. Trying to find a workaround: #4345

#4345 is only the first step to fixing the build -- it'll help us get the complete logs. Based on https://travis-ci.com/github/DynamoRIO/dynamorio/jobs/356471150, some OOM issue is causing malloc to fail.

**Pull request merged**
