### PR TITLE
i#2356: Replace tab characters with spaces in "sigcontext.h".

### PR DESCRIPTION
**Pull request by egrimley**

### CODE REVIEW

**Comment by egrimley** [comment]
Tests will fail, but I have only replaced tabs with spaces, so perhaps you can override the failure.

**Comment by fhahn** [comment]
The tests fail because the precommit suite does not allow tabs in diffs. Not sure how to override the tests though.

**Comment by egrimley** [comment]
Probably the only thing we could do would be to disable that check, then reenable it. Better to let Derek override the test "failure". I've rebased #2418 so it might be possible to rerun the tests on that one through the web interface without me having access to a real computer...

**Comment by derekbruening** [comment]
The long-term solution, as part of #2369, is to make these style checks (and new ones) look like a build or test failure instead of a script abort.

**Comment by derekbruening** [comment]
nit: the commit title was not correct for a multi-PR issue; I corrected.  As it was, the reader would assume that #2356 is only about tabs.

**Pull request merged**
