### PR TITLE
Fix flaky regex that doesn't match smaller miss rates

### PR DESCRIPTION
**Pull request by abhinav92003**
Modifies miss rate regex to allow matching rates less than 10%, by making the first digit optional.

Due to this issue, `code_api|tool.drcachesim.filter-no-i` failed in `vs2017-32` at github.com/DynamoRIO/dynamorio/actions/runs/750037355.

### CODE REVIEW

**Comment by abhinav92003** [comment]
It seems that `code_api|tool.drcachesim.filter-no-i` is run only on master merges only, but not as part of the long suite.

**Comment by derekbruening** [comment]
> It seems that `code_api|tool.drcachesim.filter-no-i` in `ci-windows/vs2017-32` is run only on master merges only, but not as part of the long suite.

Probably that's part of the #4059 effort to reduce PR time on 32-bit Windows tests.

**Review by derekbruening — APPROVED** [review]
What we should do is make unit tests (filed as #4842) with small controlled synthetic trace sequences: these tests on larger non-deterministic apps have to relax the regexes so much that they are not really testing the details.

**Comment by abhinav92003** [comment]
> What we should do is make unit tests (filed as #4842) with small controlled synthetic trace sequences: these tests on larger non-deterministic apps have to relax the regexes so much that they are not really testing the details.

I agree. There could be more cases where the regexes can be relaxed, but I'm yet to see test failures due to others.

**Pull request merged**
