### PR TITLE
Add support for custom prefetchers in drcachesim

### PR DESCRIPTION
**Pull request by conNULL**
Add constructors to the cache_simulator_t that accept a custom prefetcher factory argument.
No change to default behavior.
Added unit tests for a custom prefetcher and the existing nextline prefetcher.

### CODE REVIEW

**Comment by conNULL** [comment]
I think the one failed check is unrelated and is failing without this change as well. It appears that I can't request a review without write access to this repository, but this change should be ready for review.

**Review by brettcoon — CHANGES_REQUESTED** [review]
Thanks for the contribution.  I have a couple requests before this goes in.

**Comment by derekbruening** [comment]
> I think the one failed check is unrelated and is failing without this change as well.

Yes, Github jumped doxygen to 1.12 on the Mac VM's which broke the build there: fixed in #7001

**Review by brettcoon — APPROVED** [review]
Looks good, thanks for updating it.  I don't think you have permissions to merge it in yourself, so I can take it from here.

**Comment by conNULL** [comment]
Perfect, thanks for the review!

**Pull request merged**
