### PR TITLE
i#2156: drltrace for malware analysis

### PR DESCRIPTION
**Pull request by mxmssh**
drltrace removed from dr's dir since we decided to move the tool to DrMemory.

### CODE REVIEW

**Comment by derekbruening** [comment]
For the future, note that "myfeature" should be replaced with the actual description of the feature :)

**Comment by mxmssh** [comment]
So, what is the next step ? As I understand, we need to wait until travis and appveyor finish testing and then squash-and-merge, right?

**Comment by derekbruening** [comment]
> So, what is the next step ? As I understand, we need to wait until travis and appveyor finish testing and then squash-and-merge, right?

Right, once both are green the squash-and-merge button should become enabled automatically.  Be sure to read the wiki on editing the final commit message for future merges: here with only one commit, no edit should be necessary.

I've seen the Travis Mac VM's become over-subscribed and it sits and waits a while to get one -- that's rare though.

**Comment by mxmssh** [comment]
Is it ok that 460.3 test failed ?

**Comment by mxmssh** [comment]
code_api|linux.signal_race is failed

**Comment by derekbruening** [comment]
Is there an issue filed on it already?

**Comment by mxmssh** [comment]
Looks like https://github.com/DynamoRIO/dynamorio/issues/2019

**Comment by derekbruening** [comment]
No, #2019 is closed and is what added the test.  It's an assert, i#2066 looks like, whose priority should be raised:
```
	code_api|linux.signal_race =>  Application /home/travis/build/DynamoRIO/dynamorio/build_debug-internal-64/suite/tests/bin/linux.signal_race (28840).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/link.c:1787 !TEST(FRAG_LINKED_OUTGOING, f-flags) 
```

**Comment by mxmssh** [comment]
Mentioned here https://github.com/DynamoRIO/dynamorio/pull/2152

**Comment by derekbruening** [comment]
I went ahead and merged and deleted the branch.

**Pull request merged**
