### PR TITLE
Add the tag of the replaced cache block in the cache stats interface

### PR DESCRIPTION
**Pull request by kharbutli**
Add the tag of the replaced cache block in the cache stats interface. This would allow us to perform analyses on replaced cache blocks by extending the cache_stats_t class. Example of useful analyses: fraction of blocks that never get accessed while in the cache.

### CODE REVIEW

**Comment by derekbruening** [comment]
@AssadHashmi do we know why the AArch64 tests aren't being triggered in PR's from within the project?

**Comment by derekbruening** [comment]
run arm tests

**Comment by kharbutli** [comment]
run arm tests

**Comment by kharbutli** [comment]
run arm tests

**Comment by AssadHashmi** [comment]
run arm tests

**Comment by derekbruening** [comment]
run arm tests

**Comment by AssadHashmi** [comment]
> @AssadHashmi do we know why the AArch64 tests aren't being triggered in PR's from within the project?

It should be working now. I think it may be a user credentials issue. Have you noticed a pattern, e.g. are yours and @hgreving2304 PRs triggering tests as normal?

**Comment by derekbruening** [comment]
> > @AssadHashmi do we know why the AArch64 tests aren't being triggered in PR's from within the project?
> 
> It should be working now. I think it may be a user credentials issue. Have you noticed a pattern, e.g. are yours and @hgreving2304 PRs triggering tests as normal?

Yes, I believe mine and @hgreving2304's are triggering.  But I think @kharbutli has the same privileges as @hgreving2304 within the github project?

**Comment by AssadHashmi** [comment]
> > > @AssadHashmi do we know why the AArch64 tests aren't being triggered in PR's from within the project?
> > 
> > 
> > It should be working now. I think it may be a user credentials issue. Have you noticed a pattern, e.g. are yours and @hgreving2304 PRs triggering tests as normal?
> 
> Yes, I believe mine and @hgreving2304's are triggering. But I think @kharbutli has the same privileges as @hgreving2304 within the github project?

It looks like a Jenkins config issue rather than the GitHub side. I've made some changes. We'll see how things go.

**Comment by derekbruening** [comment]
OK, thanks for looking into it.

**Pull request merged**
