### PR TITLE
Fix includes for histogram.h and reuse_distance.h

### PR DESCRIPTION
**Pull request by snehasish**
Remove relative paths for includes in histogram.h and reuse_distance.h.

### CODE REVIEW

**Comment by fhahn** [comment]
run aarch64 tests

**Comment by fhahn** [comment]
Thank you very much for your patch. Could you explain which problem this fixes? Also, more files of drcachesim still have relative imports, e.g. https://github.com/DynamoRIO/dynamorio/blob/master/clients/drcachesim/reader/file_reader.h

**Comment by snehasish** [comment]
Apologies for the terse description. 

This fix removes the relative paths so that when reusing code for internal tools at Google, we can specify includes via -I<path>. At this time we are interested in exposing the histogram_t and reuse_distance_t tools only.

**Comment by derekbruening** [comment]
This won't affect Mac so we'll put this one through as #2809 will have to re-run anyway after removing the Mac PR tweak.

**Comment by fhahn** [comment]
Ok, @derekbruening are you doing the merge or should I? Not sure how github handles race conditions there :)

**Comment by derekbruening** [comment]
I did the merge and change the commit msg to make it part of #2006.

**Pull request merged**
