### PR TITLE
Fix strncat for OSX.

### PR DESCRIPTION
**Pull request by nilayvaish**

### CODE REVIEW

**Comment by derekbruening** [comment]
So Mac passed, but the .travis.yml change should be removed for the final commit.

**Comment by nilayvaish** [comment]
Derek, I will have to rewrite the history to strip that commit.  Would that be OK?

**Comment by derekbruening** [comment]
Don't change the history: layer a commit on top that undoes the change.  "git revert <hash>" will do that for you.

**Comment by derekbruening** [comment]
run aarch64 tests

**Pull request merged**
