### PR TITLE
Various fixes to EVEX.b handling

### PR DESCRIPTION
**Pull request by khuey**
Largely for #4534. I'd like to get feedback on this before I do the rest of the bcst operands.

One thing I'd be particularly interested in is where the tests for instructions that _don't_ decode are.

### CODE REVIEW

**Comment by derekbruening** [comment]
It seems odd to file separate issues on the small problems (#4536, #4537) but then not fix them separately and instead bundle them into something else: I would expect a separate PR per filed issue.

**Comment by derekbruening** [comment]
> One thing I'd be particularly interested in is where the tests for instructions that don't decode are.

The api.dis test may be the only current one trying to cover a variety of encodings.  The api.ir* tests have some particular tests (e.g., encodings invalid in 32-bit mode but valid in 64-bit).  (There are others testing fault handling for illegal instrs but they do not cover many encodings.)

**Comment by khuey** [comment]
Alright this looks good. The various pieces are self explanatory, I think. Throwing the vpermb patch in the middle there was a mistake in retrospect but disentangling it would be rather painful because of the decode table renumbering.

**Comment by khuey** [comment]
Because of #4555 I think we need a different approach here.

**Pull request closed without merging**
