### PR TITLE
i#3692:Added pext encoding fix

### PR DESCRIPTION
**Pull request by johnfxgalea**
Arranges pext's encoding which otherwise leads to an illegal instruction exception.

Fixes: #3692

### CODE REVIEW

**Comment by johnfxgalea** [comment]
Where should I include a regression test please? Was thinking drreg-test.dll.c but I don't think this is ideal. Thoughts?

**Comment by hgreving2304** [comment]
> AppVeyor build failed

Please check, most likely, a previous "invalid" disassembler output now prints the pext instruction. In that case, you can update the third_party/binutils/test_decenc/drdecode_decenc_x86[_64].expect file(s).

**Comment by AssadHashmi** [comment]
run arm tests

**Comment by johnfxgalea** [comment]
The following was the diff:

```
diff drdecode_decenc_x86.expect-expect drdecode_decenc_x86.expect-out
1449c1449
<  c4 e2 7a f5 00       bzhi   (%eax), %eax, %eax
---
>  c4 e2 7a f5 00       pext   (%eax), %eax, %eax
6236,6237c6236,6237
<  c4 e2 62 f5 f0       bzhi   %eax, %ebx, %esi
<  c4 e2 62 f5 31       bzhi   (%ecx), %ebx, %esi
---
>  c4 e2 62 f5 f0       pext   %eax, %ebx, %esi
>  c4 e2 62 f5 31       pext   (%ecx), %ebx, %esi
6252,6254c6252,6254
<  c4 e2 62 f5 f0       bzhi   %eax, %ebx, %esi
<  c4 e2 62 f5 31       bzhi   (%ecx), %ebx, %esi
<  c4 e2 62 f5 31       bzhi   (%ecx), %ebx, %esi
---
>  c4 e2 62 f5 f0       pext   %eax, %ebx, %esi
>  c4 e2 62 f5 31       pext   (%ecx), %ebx, %esi
>  c4 e2 62 f5 31       pext   (%ecx), %ebx, %esi
79676c79676
<  c4 e2 7a f5 00       bzhi   (%eax), %eax, %eax
---
>  c4 e2 7a f5 00       pext   (%eax), %eax, %eax

```

**Comment by johnfxgalea** [comment]
I don't have a machine for testing x86_64 at the moment.

**Comment by hgreving2304** [comment]
> The following was the diff:

Looks ok.

**Comment by hgreving2304** [comment]
run arm tests

**Comment by hgreving2304** [comment]
Thanks!

**Pull request merged**
