### PR TITLE
i#3230 split traces: parallelize raw2trace

### LINKED ISSUE #3129: Enable concurrent raw trace processing by factoring out core conversion functionality
Trace conversion (raw2trace) is CPU bound. This issue tracks factoring out the core conversion logic, such that extensions may be created, employing specialized parallelization techniques, to speed up trace processing.

### PR DESCRIPTION
**Pull request by derekbruening**
Adds concurrent post-processing of raw thread files by default.
Adds a new option -jobs for selecting the worker thread pool size.
Uses a simple static round-robin work assignment of traced threads to
worker threads.

Splits the decode cache into a separate cache per worker, to keep it
lockless.

Adds a per-traced-thread last_decode_pc mini-cache to speed up rep
string loop processing.

Issue: #3230
Fixes #3129

### CODE REVIEW

**Comment by derekbruening** [comment]
I can't reproduce this release build pthread link issue on AArch64 when I log in to the same Jenkins machine!  Unsure of what is going on.

**Comment by derekbruening** [comment]
run arm tests

**Comment by AssadHashmi** [comment]
> I can't reproduce this release build pthread link issue on AArch64 when I log in to the same Jenkins machine! Unsure of what is going on.

I noticed a link_with_pthread() call has been added to clients/drcachesim/CMakeLists.txt and the failure is complaining about "undefined reference to `pthread_create'". Not sure if that has anything to do with it. I'll try to reproduce the failure.

**Comment by derekbruening** [comment]
> > I can't reproduce this release build pthread link issue on AArch64 when I log in to the same Jenkins machine! Unsure of what is going on.
> 
> I noticed a link_with_pthread() call has been added to clients/drcachesim/CMakeLists.txt and the failure is complaining about "undefined reference to `pthread_create'". Not sure if that has anything to do with it. I'll try to reproduce the failure.

Yes, link_with_pthread adds libpthread to the link line for the drmemtrace_raw2trace library.  That should then appear on the link line for executables like drraw2trace and drcachesim.  And it does in every build dir except release build aarch64 on Jenkins!  Compare:

```
derek@dynamorio-nightly:~$ grep -r -c pthread /data/jenkins_root/workspace/DynamoRIO-AArch64-Precommit/build/build_debug-internal-64/clients/drcachesim/CMakeFiles/*.dir/link.txt | grep :1
/data/jenkins_root/workspace/DynamoRIO-AArch64-Precommit/build/build_debug-internal-64/clients/drcachesim/CMakeFiles/drcachesim.dir/link.txt:1
/data/jenkins_root/workspace/DynamoRIO-AArch64-Precommit/build/build_debug-internal-64/clients/drcachesim/CMakeFiles/drraw2trace.dir/link.txt:1

derek@dynamorio-nightly:~$ grep -r -c pthread /data/jenkins_root/workspace/DynamoRIO-AArch64-Precommit/build/build_release-external-64/clients/drcachesim/CMakeFiles/*.dir/link.txt | grep :1
```

**Comment by derekbruening** [comment]
(Should have done `grep -v :0` or `grep -o` -- no, there are no files w/ >1 ref :))

**Comment by derekbruening** [comment]
When I make a build dir locally that should match the build suite dir "release-external-64" it has the link:
```
derek@dynamorio-nightly:~/build$ cmake -DDEBUG=OFF -DINTERNAL=OFF -DBUILD_TESTS=ON /data/jenkins_root/workspace/DynamoRIO-AArch64-Precommit/
derek@dynamorio-nightly:~/build$ grep -o pthread clients/drcachesim/CMakeFiles/*.dir/link.txt
clients/drcachesim/CMakeFiles/drcachesim.dir/link.txt:pthread
clients/drcachesim/CMakeFiles/drraw2trace.dir/link.txt:pthread
```

**Comment by derekbruening** [comment]
Hmm actually BUILD_TESTS is OFF for the suite release-external-64 build dir and I can repro when I turn it off, including on an Intel machine:

```
$ cmake ../src
$ grep -o pthread clients/drcachesim/CMakeFiles/*.dir/link.txt
$ rm -rf *; cmake -DBUILD_TESTS=ON ../src
$ grep -o pthread clients/drcachesim/CMakeFiles/*.dir/link.txt
clients/drcachesim/CMakeFiles/drcachesim.dir/link.txt:pthread
clients/drcachesim/CMakeFiles/drraw2trace.dir/link.txt:pthread
clients/drcachesim/CMakeFiles/opcode_mix_launcher.dir/link.txt:pthread
clients/drcachesim/CMakeFiles/tool.drcacheoff.burst_replace.dir/link.txt:pthread
clients/drcachesim/CMakeFiles/tool.drcacheoff.burst_threadfilter.dir/link.txt:pthread
clients/drcachesim/CMakeFiles/tool.drcacheoff.burst_threads.dir/link.txt:pthread
clients/drcachesim/CMakeFiles/tool.drcacheoff.raw2trace_io.dir/link.txt:pthread
```

**Comment by derekbruening** [comment]
But Travis succeeded -- does that mean Travis has BUILD_TESTS=ON while this Jenkins has OFF?

I think I found the reliance on BUILD_TESTS in the code and can fix it but I'm confused about why Travis succeeded.

**Comment by derekbruening** [comment]
> I'm seeing same behaviour as you on a manual build. I will check the Jenkins instance later as I have to head home now.

Thanks.  I'm not sure why BUILD_TESTS would be different: I believe it should be off based on runsuite.cmake.

**Comment by AssadHashmi** [comment]
> > But Travis succeeded -- does that mean Travis has BUILD_TESTS=ON while this Jenkins has OFF?
> 
> I'm seeing same behaviour as you on a manual build. I will check the Jenkins instance later as I have to head home now.

That must be the case AFAICT.

I checked Jenkins DynamoRIO-AArch64-Precommit. It runs:
`suite/runsuite_wrapper.pl travis`
which calls runsuite.cmake. In that, the release-external-64 build does not set BUILD_TESTS to ON.

If Travis builds on x86 rather than AArch64, there may be cross-build settings which could explain the odd behaviour.

**Comment by AssadHashmi** [comment]
> But Travis succeeded -- does that mean Travis has BUILD_TESTS=ON while this Jenkins has OFF?

That must be the case AFAICT.                                                    
                                                                                 
I checked Jenkins DynamoRIO-AArch64-Precommit. It runs:                          
suite/runsuite_wrapper.pl travis                                                 
which calls runsuite.cmake. The release-external-64 build does not set BUILD_TESTS to ON.
                                                                                 
If Travis builds on x86 rather than AArch64, there may be cross-compile settings which could explain the odd behaviour.

**Pull request merged**
