### PR TITLE
i#4297: Fix source operand size for cvtps2pd

### PR DESCRIPTION
**Pull request by rocallahan**
The source operand is only 8 bytes but can come from an XMM register.

Issue: #4297

### CODE REVIEW

**Comment by rocallahan** [comment]
I'm not sure what kind of test you would want here.

**Comment by derekbruening** [comment]
If you are able it would be great to include fixes to `cvtps2pi1 and `vcvtps2pd` as well?

Re: tests: if you `git grep` for the opcode you will see the two sets of tests: internal consistency in suite/tests/api/ and disasm ground truth matching in third_party/binutils/test_decenc.  Unfortunately 8_of_16 vs 16 is not distinguishable in Intel syntax but at least the api/ test has to be updated to match the size for a memory arg.

**Comment by rocallahan** [comment]
I'd prefer to not fix `vcvtps2pd` since that seems quite a bit harder, and there is the issue of why the tests pass when they should not.

**Comment by rocallahan** [comment]
> there is the issue of why the tests pass when they should not.

OK I guess there is no issue there, but I still don't have a firm grasp of the right way to fix `vcvtps2pd`.

**Comment by derekbruening** [comment]
> > I'd prefer to not fix `vcvtps2pd` since that seems quite a bit harder, and there is the issue of why the tests pass when they should not.
>
> OK I guess there is no issue there, but I still don't have a firm grasp of the right way to fix vcvtps2pd.

Fair enough.  We'll leave the issue open for vcvtps2pd and fixing the tests.

**Comment by derekbruening** [comment]
run arm tests

**Pull request merged**
