### PR TITLE
i#3544 RV64: One step closer to running Hello World

### PR DESCRIPTION
**Pull request by ksco**
In this patch, along with other Pending PRs of mine (namely #6070 #6064 #6062 #6061), we're getting closer to `drrun` a simple hello world program. This patch contains the following changes:

1. Added machine type support for ELF hdr verification
2. Fixed various atomics and TLS issues

With this patch, running a simple program like this one:
```
.global _start
_start: li      a0, 1
        la      a1, helloworld
        li      a2, 14
        li      a7, 64
        ecall

        li      a0, 0
        li      a7, 93
        ecall

.data
helloworld:     .ascii "Hello, World!\n"
```
Gives meaningful error message(will segfault before):

```
debian@lpi4a:/media/debian/Data/dynamorio/build$ ./bin64/drrun -verbose hello
INFO: default root: /media/debian/Data/dynamorio/build/bin64/..
INFO: default toolconfig dir: /media/debian/Data/dynamorio/build/bin64/../tools
INFO: targeting application: "/media/debian/Data/dynamorio/build/hello"
INFO: app cmdline:  "hello"
INFO: configuration directory is "/home/debian/.dynamorio"
INFO: will exec /media/debian/Data/dynamorio/build/hello
<Application /media/debian/Data/dynamorio/build/hello (214671). Cannot correctly handle received signal 11 in thread 214671: default action in native thread.>
```

I'll keep trying to fix bugs in a follow-up PR.

Issue #3544

### CODE REVIEW

**Comment by ksco** [comment]
@abhinav92003 Can you review the PRs mentioned in the description? With more and more pending PRs, it can become difficult to continue developing pretty quickly, thanks!

**Comment by abhinav92003** [comment]
> @abhinav92003 Can you review the PRs mentioned in the description? With more and more pending PRs, it can become difficult to continue developing pretty quickly, thanks!

I reviewed some 7 PRs: 5 of them I've approved after my suggested changes were made, 2 of them (#6071, #6065) still have unresolved comments. Please request re-review when they are addressed. If there are other PRs, feel free to add me as a reviewer on the UI.

**Comment by ksco** [comment]
Thanks!

> If there are other PRs, feel free to add me as a reviewer on the UI.

I don't have permission to assign reviewers currently.

**Comment by abhinav92003** [comment]
> I don't have permission to assign reviewers currently.

I sent you an invite to our Committers list. You should be able to assign reviewers and use branches on this repository now. @derekbruening FYI.

**Comment by ksco** [comment]
Thanks. Also, I converted this into a draft, I'll mark it ready when hello world actually works.

**Comment by ksco** [comment]
Now, the TLS initialization stuff is happy, it begins to segfault in `ir/instr_shared.c`, that's some progress.

**Comment by ksco** [comment]
Making a hello world program run requires more work than I think, which is too large for a single PR.

**Pull request closed without merging**
