### PR TITLE
Implement attach for both windows and linux

### PR DESCRIPTION
**Pull request by summershrimp**
For linux, we use ptrace() to inject dynamorio to running process.
For windows, we get target process handle using DebugActiveProcess()
and inject with original dr_inject_process_inject().

### CODE REVIEW

**Comment by summershrimp** [comment]
I think it's only working on x86/x64 since inject_ptrace is not available for arm

**Comment by AssadHashmi** [comment]
run arm tests

**Comment by AssadHashmi** [comment]
run arm tests

**Comment by derekbruening** [comment]
@summershrimp are you planning to resume this PR?

**Comment by summershrimp** [comment]
Yes, but a little busy these days. I'll do it asap

**Comment by derekbruening** [comment]
This should reference the attach issues: #38, #725

**Comment by derekbruening** [comment]
Pasting from https://github.com/DynamoRIO/dynamorio/issues/4601#issue-761345546

> Hello,
>
> I'm trying to finish this PR 3328 because I need to be able to attach DynamoRIO to an executed process (i use it for fuzzing with winAFL).
> I fixed everything and I can compile now.
> I just need some help to test it because I don't really get which process I have to run, but since Summershrimp added the -attach to DRCONFIG it's probably with drconfig.exe?
>
> Thank you and have a nice day!

Thank you for contributing!

That drdploy.c file turns into drconfg.exe, drrun.exe, and drinject.exe.  The -attach would apply only to drrun.exe and drinject.exe.  drinject.exe is rarely used so it would be drrun.exe for a manual test.  See https://dynamorio.org/dynamorio_docs/page_deploy.html#win_deploy

As requested above (https://github.com/DynamoRIO/dynamorio/pull/3328#discussion_r246553938) we would want an automated test added to the suite as well.

**Comment by summershrimp** [comment]
I would restart working on this PR soon

**Comment by raefko** [comment]
Hello,
Thank you @derekbruening fo your answer, I'm new to DynamoRIO and I'm trying to better understand how it works.
I took a look at the code and the issues/PR you mentioned before and I'm starting to get how it works.
I think that the -attach doesn't really do what I thought. Is it an option we add before the " -- <app and args to run> " (seems like yes). Or the option is here to replace the running of a process.
For example :
I have notpad.exe that is running, I get the pid which is XYZ, and I just run 
```./drrun.exe [options] -attach XYZ```
I mean, what is the main use of the -attach option?

Thank you and have a nice day!

**Comment by derekbruening** [comment]
> I think that the -attach doesn't really do what I thought. Is it an option we add before the " -- app and args to run " (seems like yes). Or the option is here to replace the running of a process.

You're asking why this PR addes an -attach flag but doesn't update the usage message which says to always pass "-- app"?  Agreed, it should update the usage message to say that an application should not be passed, and should complain about it (I think the PR code would just silently ignore the passed app now).

**Comment by raefko** [comment]
> > I think that the -attach doesn't really do what I thought. Is it an option we add before the " -- app and args to run " (seems like yes). Or the option is here to replace the running of a process.
> 
> You're asking why this PR addes an -attach flag but doesn't update the usage message which says to always pass "-- app"? Agreed, it should update the usage message to say that an application should not be passed, and should complain about it (I think the PR code would just silently ignore the passed app now).

Okey i will fix that thanks!

**Comment by raefko** [comment]
> I would restart working on this PR soon

Hello,
Can i have your e-mail please? I think that the one in your github profile isn't the current one.

**Comment by ajohnston9** [comment]
Any progress here? This is a critical feature for me.

**Comment by ajohnston9** [comment]
Any progress here? This is a critical feature for me.

**Comment by derekbruening** [comment]
#5019 which includes the Linux portion of the changes here is merged -- but the Windows portion of this PR is not yet merged.

**Comment by derekbruening** [comment]
With PR #5075 adding Windows attach by building on this PR I think everything here is now merged so we can close this.  Thank you for this initial PR: even though it didn't get merged it seeded the subsequent PR's.

**Pull request closed without merging**
