### PR TITLE
Add the ability to set custom system search paths.

### PR DESCRIPTION
**Pull request by hgreving2304**
Adds the ability to the private loader to set DR_CUSTOM_SYSTEM_PATH in order to add
system paths to the search list. This can be used for testing or for environments
that are specific to the user where hardcoding the path in the private loader should
be avoided.

DR_CUSTOM_SYSTEM_PATH can be used like LD_LIBRARY_PATH. The paths will be looked up
after DynamoRIO's internal system paths.

### CODE REVIEW

**Comment by derekbruening** [comment]
But why would this be needed when the private loader already supports the standardized LD_LIBRARY_PATH?

**Comment by hgreving2304** [comment]
> But why would this be needed when the private loader already supports the standardized LD_LIBRARY_PATH?

In environment G, adding it to LD_LIBRARY_PATH doesn't work and leads to a symbol error when loading drrun. I suspect an ordering issue with rpath, somehow libpthread fails to link in this env when the path is in LD_LIBRARY_PATH (besides libpthread being there in the first place, but that's a different question). The path needs to be part of the system search paths. Instead of adding a new system search path to the loader, I thought we introduce this environment variable here that makes it more flexible.

**Comment by derekbruening** [comment]
> > But why would this be needed when the private loader already supports the standardized LD_LIBRARY_PATH?
> 
> In environment G, adding it to LD_LIBRARY_PATH doesn't work and leads to a symbol error when loading drrun. I suspect an ordering issue with rpath, somehow libpthread fails to link in this env when the path is in LD_LIBRARY_PATH (besides libpthread being there in the first place, but that's a different question). The path needs to be part of the system search paths. Instead of adding a new system search path to the loader, I thought we introduce this environment variable here that makes it more flexible.

It sounds like the reason LD_LIBRARY_PATH causes problems is not known.  Shouldn't that be understood before adding new features which may or may not really be necessary?

I could see LD_LIBRARY_PATH having the downside of affecting the app's loader too.  There is still rpath/runpath which seems a good solution for a particular client build.  If we wanted to add some other mechanism of affecting the private loader's search paths, I would vote for a DR runtime option, not an env var: everything else about DR is controlled by options so I would stick to that and not have some other type of interface.

**Comment by hgreving2304** [comment]
> > > But why would this be needed when the private loader already supports the standardized LD_LIBRARY_PATH?
> > 
> > 
> > In environment G, adding it to LD_LIBRARY_PATH doesn't work and leads to a symbol error when loading drrun. I suspect an ordering issue with rpath, somehow libpthread fails to link in this env when the path is in LD_LIBRARY_PATH (besides libpthread being there in the first place, but that's a different question). The path needs to be part of the system search paths. Instead of adding a new system search path to the loader, I thought we introduce this environment variable here that makes it more flexible.
> 
> It sounds like the reason LD_LIBRARY_PATH causes problems is not known. Shouldn't that be understood before adding new features which may or may not really be necessary?
> 
> I could see LD_LIBRARY_PATH having the downside of affecting the app's loader too. There is still rpath/runpath which seems a good solution for a particular client build. If we wanted to add some other mechanism of affecting the private loader's search paths, I would vote for a DR runtime option, not an env var: everything else about DR is controlled by options so I would stick to that and not have some other type of interface.

Prob. better to move offline since it's related to Google internals.

Can't answer "Shouldn't that be understood before adding new features which may or may not really be necessary?" here.

**Comment by hgreving2304** [comment]
xref #3863 
We agreed on closing this one.

**Pull request closed without merging**
