### PR TITLE
i#4865 emulate: Use new API in memval_simple + memtrace_x86

### PR DESCRIPTION
**Pull request by derekbruening**
Uses the new emulation instrumentation interface in the memval_simple
and memtrace_x86 samples.

Here's the output of memval_simple before:
    $ bin64/drrun -c api/bin/libmemval_simple.so -- suite/tests/bin/allasm_repstr && cat `ls -1td api/bin/*.log|head -1`
    0x402000: movs  1 41
    0x402001: movs  1 64
    0x402002: movs  1 69
    0x402003: movs  1 6f
    0x402004: movs  1 73
And after:
    0x402000: rep movs  1 41
    0x402001: rep movs  1 64
    0x402002: rep movs  1 69
    0x402003: rep movs  1 6f
    0x402004: rep movs  1 73

Issue: #4865

### CODE REVIEW

**Comment by derekbruening** [comment]
Hmm, there is some heap bug in memval that doesn't show up in the local allasm testing -- if you want to wait to review that's reasonable, or if you do review maybe you can help find it.

**Review by abhinav92003 — APPROVED** [review]

**Comment by abhinav92003** [comment]
> Hmm, there is some heap bug in memval that doesn't show up in the local allasm testing -- if you want to wait to review that's reasonable, or if you do review maybe you can help find it.

Couldn't find it yet. May need to look at the instrumented sequence.

**Comment by derekbruening** [comment]
> > Hmm, there is some heap bug in memval that doesn't show up in the local allasm testing -- if you want to wait to review that's reasonable, or if you do review maybe you can help find it.
> 
> Couldn't find it yet. May need to look at the instrumented sequence.

Fixed now.  Ready for review.

**Review by abhinav92003 — APPROVED** [review]

**Comment by derekbruening** [comment]
Jenkins failure is #4954 tool.drcachesim.threads-with-config-file again!  Happening more frequently all of a sudden.

**Pull request merged**
