### PR TITLE
i#2626: AArch64 decode: Add CMEQ CMGE CMGT CMLT

### PR DESCRIPTION
**Pull request by AssadHashmi**
Adds the following instructions to the codec:

CMEQ Vd.T, Vn.T, Vm.T
CMEQ Vd, Vn, Vm
CMEQ Vd.T, Vn.T, #0
CMEQ Vd, Vn, #0
CMGE Vd.T, Vn.T, Vm.T
CMGE Vd, Vn, Vm
CMGE Vd.T, Vn.T, #0
CMGE Vd, Vn, #0
CMGT Vd.T, Vn.T, Vm.T
CMGT Vd, Vn, Vm
CMGT Vd.T, Vn.T, #0
CMGT Vd, Vn, #0
CMLT Vd.T, Vn.T, #0
CMLT Vd, Vn, #0

Issue: #2626

### CODE REVIEW

**Review by MDevereau — APPROVED** [review]

**Comment by AssadHashmi** [comment]
Hi @derekbruening all but the AArch64 precommit tests are hanging on `Expected — Waiting for status to be reported`.
There's no links which I can click on to take me to the test pages.

This started happening yesterday. I have done a couple more commits since then and tests are still hanging, so doesn't look like an intermittent triggering issue.

**Comment by derekbruening** [comment]
> Hi @derekbruening all but the AArch64 precommit tests are hanging on `Expected — Waiting for status to be reported`.
> There's no links which I can click on to take me to the test pages.
> 
> This started happening yesterday. I have done a couple more commits since then and tests are still hanging, so doesn't look like an intermittent triggering issue.

Tests ran on other PR's late last night so it seems like it's just been a few hours?  Once before something like this happened and it seemed to be a Github backend issue which they resolved after a few hours.  IIRC we found a report for that earlier one -- they don't have a regular tracker but a community section of the site where such problems are reported?

**Comment by AssadHashmi** [comment]
> Tests ran on other PR's late last night so it seems like it's just been a few hours? Once before something like this happened and it seemed to be a Github backend issue which they resolved after a few hours. IIRC we found a report for that earlier one -- they don't have a regular tracker but a community section of the site where such problems are reported?

@MDevereau's latest PR ran all the tests a couple of hours ago https://github.com/DynamoRIO/dynamorio/pull/4988
Have you got a link for the community section of the site where problems can be reported, anything more specific than https://github.community ?

**Comment by derekbruening** [comment]
> > Tests ran on other PR's late last night so it seems like it's just been a few hours? Once before something like this happened and it seemed to be a Github backend issue which they resolved after a few hours. IIRC we found a report for that earlier one -- they don't have a regular tracker but a community section of the site where such problems are reported?
> 
> @MDevereau's latest PR ran all the tests a couple of hours ago #4988
> Have you got a link for the community section of the site where problems can be reported, anything more specific than https://github.community ?

No, the issue reporting is not ideal in general for Github: e.g., there is a bug in enforcing use of the bug templates if authentication is done late, and there was no tracker to report it: I had to send them an email instead, so there is no record to point anyone else at, and it's still not fixed.  For Actions I recall just seraching and finding pages like https://github.community/c/code-to-cloud/github-actions/41

**Pull request merged**
