### PR TITLE
i#1312 AVX-512 support: Bugfix, EVEX.V' is bit inverted.

### PR DESCRIPTION
**Pull request by hgreving2304**
Fixes EVEX decoder and inverted logic for V'. Rountrips do not test this kind of
bug. More thorough testing will be added through disassembler tests once more
instructions have been enabled.

Issue: #1312

### CODE REVIEW

**Comment by derekbruening** [comment]
I had assumed your workflow included comparing disassembly to binutils for the particular instructions being added.

**Comment by hgreving2304** [comment]
> I had assumed your workflow included comparing disassembly to binutils for the particular instructions being added.

Bug was hidden behind double negative and popped up with patch in https://github.com/DynamoRIO/dynamorio/pull/3630 when a new operand type was added that is of type 'H' + AVX-512.

**Comment by derekbruening** [comment]
> > I had assumed your workflow included comparing disassembly to binutils for the particular instructions being added.
>
> Bug was hidden behind double negative and popped up with patch in #3630 when a new operand type was added that is of type 'H' + AVX-512.

But it's a bug that shows up as something incorrect in the instructions added in #3630?  Your description implies it would have been found by comparing disassembly to some other decoder before posting the pull request.  Please add that to your workflow for future patches.  It doesn't have to be binutils: ones with convenient command line decoding may be simpler (capstone, llvm) and #2987 may help.

**Comment by hgreving2304** [comment]
> > > I had assumed your workflow included comparing disassembly to binutils for the particular instructions being added.
> > 
> > 
> > Bug was hidden behind double negative and popped up with patch in #3630 when a new operand type was added that is of type 'H' + AVX-512.
> 
> But it's a bug that shows up as something incorrect in the instructions added in #3630? Your description implies it would have been found by comparing disassembly to some other decoder before posting the pull request. Please add that to your workflow for future patches. It doesn't have to be binutils: ones with convenient command line decoding may be simpler (capstone, llvm) and #2987 may help.

The invert was done at the wrong place, see this patch. The disassembly for the already added instructions looked ok until now. Disassembly for instructions added in #3630 started to look incorrect and I realized the inversion error. i.e. I am already comparing to objdump.

**Pull request merged**
