### PR TITLE
i#3867: Extend reg_is_simd() to zmm.

### LINKED ISSUE #3867: Extend reg_is_simd to consider ZMM registers as well.
Current implementation of reg_is_simd does not consider ZMM as simd. 

```
bool
reg_is_simd(reg_id_t reg)
{
    return reg_is_xmm(reg) /*includes ymm*/ || reg_is_mmx(reg);
}
```

Issue relates to extending reg_is_simd to checking ZMM registers as well.

### PR DESCRIPTION
**Pull request by johnfxgalea**
Extends reg_is_simd to consider ZMM registers.

Fixes #3867

### CODE REVIEW

**Comment by hgreving2304** [comment]
Thank you!

**Comment by johnfxgalea** [comment]
Someone please run arm tests.

**Comment by hgreving2304** [comment]
run arms tests

**Comment by hgreving2304** [comment]
run arm tests

**Comment by hgreving2304** [comment]
run arm tests

**Comment by johnfxgalea** [comment]
Did Appveyor get stuck?

**Pull request merged**
