### PR TITLE
WIP Vc2017 fix

### PR DESCRIPTION
**Pull request by firodj**
try to Fix build on VC2017, but still so many Warnings to disable (maybe need to FIX)

https://github.com/DynamoRIO/dynamorio/issues/2924

### CODE REVIEW

**Comment by derekbruening** [comment]
Marking "WIP" (Work In Progress)

**Comment by AssadHashmi** [comment]
run arm tests

**Comment by firodj** [comment]
hi @derekbruening , I think this issue should be Closed also by: https://github.com/DynamoRIO/dynamorio/pull/3860
wdyt ?

**Comment by derekbruening** [comment]
Yes, closing.

**Pull request closed without merging**
