### PR TITLE
i#2443 AArch64 codec: Add exhaustive encoder/decoder consistency test.

### PR DESCRIPTION
**Pull request by egrimley**
Add the program "api.reenc-a64", which decodes and then reencodes all
32-bit words in a given range, checking for consistency. On server
hardware the full range (0-0xffffffff) is likely to take less than
two hours divided by the number of available cores. This test can be
run when modifying the encoder/decoder or when preparing a release.

Change-Id: I4941bc16b03b4a95834fabf70fea40cb465e0275

### CODE REVIEW

**Comment by fhahn** [comment]
Could you maybe document how to run this test, maybe in a comment in reenc-a64.c?

**Comment by fhahn** [comment]
Can one of the admins verify this patch?

**Comment by fhahn** [comment]
run aarch64 tests

**Comment by egrimley** [comment]
There's a usage message. I could put in the comment at the start of the file something like:
```
... If you have a single machine with two cores you could run:
* api.reenc-a64 0x00000000 0x7fffffff > log0 &
* api.reenc-a64 0x80000000 0xffffffff > log1 &
*/
```

Would that help?

**Comment by fhahn** [comment]
Yep that sounds good, thank you!

I think we could do a nightly run on the public AArch64 machine we have. I don't know much about CDash, but presumably we could add a new suite containing just this one test, to get the results submitted to CDash and to the mailing list. What do you think @derekbruening ?
I don't  think it would be a good idea to add it to the current nightly suite though, as we run them with multiple configurations on the same machine.

**Comment by egrimley** [comment]
I'm not sure it's worth running this test automatically. However, perhaps something should be done to make sure it doesn't get completely forgotten about. Is there a pre-release check list where it could be mentioned, for example?

**Comment by fhahn** [comment]
rerun aarch64 tests

**Comment by fhahn** [comment]
I'm currently running the test on another AArch64 machine.  Looks like `LD_LIBRARY_PATH=lib64/debug/` is also required.

**Comment by egrimley** [comment]
Yes, but that might depend on whether you have installed DynamoRIO, and it certainly depends on whether you built with DEBUG. You probably want to run this program without DEBUG.

**Pull request merged**
