### PR TITLE
i4134: Pass fragment tag to drbbdup instrum routines

### PR DESCRIPTION
**Pull request by johnfxgalea**
Arranges instrumentation call-back functions of drbbdup to accept the passing of tag values.

Issue: #4134

### CODE REVIEW

**Comment by johnfxgalea** [comment]
Think about it now, I should also pass for_trace but I'll draw up another PR for that.

**Comment by johnfxgalea** [comment]
@derekbruening Something weird happened on Mac. Was this the failure which you couldn't reproduce last month? I couldn't find an entry on the issues page.

**Comment by derekbruening** [comment]
I remember #3127 and #4022 -- is that what you mean?

**Comment by johnfxgalea** [comment]
run arm tests

**Comment by johnfxgalea** [comment]
Issues a new page for the MAC OS failure: #4156

**Comment by derekbruening** [comment]
I am seeing strange Mac failures in #4150 but it looks different: the log ends early as though it's a timeout but it doesn't report a timeout.  A re-run went green on one instance of this.

**Comment by johnfxgalea** [comment]
> I am seeing strange Mac failures in #4150 but it looks different: the log ends early as though it's a timeout but it doesn't report a timeout. A re-run went green on one instance of this.

hmm, they both seem to be trigger similar failures: vmareas.c:1511 start <= end || end == NULL
Could it be the same root-cause? hmm

**Comment by johnfxgalea** [comment]
run arm tests

**Comment by johnfxgalea** [comment]
Thank you for the review!

**Comment by johnfxgalea** [comment]
Going ahead with the merge. Test failure is due to #4156

**Pull request merged**
