### PR TITLE
i#4719 qemu: Add support for running tests under QEMU

### PR DESCRIPTION
**Pull request by derekbruening**
When cross-compiling, inserts QEMU commands into each test command line.
Increases the test timeouts by 4x to account for emulation overhead.

Adds GA CI support by installing QEMU and enabling running tests for
the AArchXX cross-compilation jobs.  For now, limits the tests to
those marked with a new label RUNS_ON_QEMU, which starts out added to
the ~1/3 of tests that currently pass.  As we get more tests to work
we may want to separate the jobs if they take too much time.

Issue: #4719

### CODE REVIEW

**Comment by derekbruening** [comment]
Hmm, this passes on my local machine, which is a debian variant with qemu 5.2.0.  But here it hits two problems:

```
2021-02-19T20:21:04.9375582Z 6: qemu: Unsupported syscall: 398
2021-02-19T20:21:04.9377281Z 6: <Application /home/runner/work/dynamorio/dynamorio/build_arm-debug-internal-32/suite/tests/bin/common.broadfun (14909).  Internal Error: DynamoRIO debug check failure: /home/runner/work/dynamorio/dynamorio/core/unix/signal.c:1580 rc == 0 IF_VMX86(|| (sig >= 63 && rc == -EINVAL))
```

The assert is #4627 which was also seen on a different machine in the past.  It's sigaction failing, which is weird.  Related to this being an old qemu?  If we can repro we can see what signal it is.

The unknown syscall is a newly seen problem: 398 (or 293 for aarch64) is rseq.  I'm guessing it's an older QEMU since my 5.2.0 doesn't complain.  It doesn't seem to be fatal: though it might cause golden-output tests to fail?  So we may have to get a newer QEMU on the system.

This is what was installed:
```
2021-02-19T20:18:42.4340526Z Setting up qemu-user (1:2.5+dfsg-5ubuntu10.49) ...
2021-02-19T20:18:42.4565040Z Setting up qemu-user-binfmt (1:2.5+dfsg-5ubuntu10.49) ...
```

**Comment by derekbruening** [comment]
GA has Ubuntu 20.04 which has qemu-user 4.2.  I tried it and indeed the rseq message goes away.  But the
sigaction assert is still there!  I guess I'll try to set up a VM to repro and see what is going on.

**Comment by derekbruening** [comment]
OK, now we have green aarch tests under emulation.  It's only 1/3 of the tests but it is a great starting point:
```
arm-debug-internal-32: all 68 tests passed
arm-debug-internal-64: all 76 tests passed
```

This pushes the aarchxx-cross-compile job to 20m so maybe we should split it.

**Comment by derekbruening** [comment]
OK it is all good except the old job name is still listed as required.  I went and edited the required jobs settings but it doesn't seem to be affecting what was already run here so ignore the uncompleted job for this PR.

**Review by abhinav92003 — APPROVED** [review]

**Comment by abhinav92003** [comment]
This is great! Thanks for adding Qemu for ARM32. 

So this new suite is `aarch32-cross-compile` right? It's showing yellow.

**Comment by derekbruening** [comment]
> So this new suite is aarch32-cross-compile right? It's showing yellow.

Oh that's the name I gave it in the first commit that split up 32 and 64, but then I changed the name arm-cross-compile to match our internal conventions, and that one is green and taking 10 mins (just like aarch64-cross-compile).  Interesting that it has the aarch32 one marked as required -- at first glance I thought that was the old aarchxx-cross-compile.  Maybe it inherited from that one?  In any case I think a new PR will not show the old name and will be all good.

**Comment by derekbruening** [comment]
> This is great! Thanks for adding Qemu for ARM32.

Thanks for pushing for it -- I had assumed it would be a lot more work than it was.  Though I think to get the other 2/3 of the tests will be a lot of work: I think there's a combination of DR bitrot on ARM, work to get QEMU into command lines, flakiness/slowness exaggerted by QEMU, and QEMU bugs.  But no rush on that: just having these ~70 tests is a great sanity check to avoid completely breaking ARM, and another validation layer for AArch64 beyond Jenkins.

**Comment by derekbruening** [comment]
> > So this new suite is aarch32-cross-compile right? It's showing yellow.
> 
> Oh that's the name I gave it in the first commit that split up 32 and 64, but then I changed the name

Turns out I marked the wrong name as required in the github settings which is why it was still listed.  Fixed now.

**Pull request merged**
