### PR TITLE
Fix for assert in offline tracer with L0_filter

### PR DESCRIPTION
**Pull request by prasun3**
Fixes assert (#4943) by using a 16-bit immediate instead of 8-bit because max_bb_instrs can be 256 (default) or larger

### CODE REVIEW

**Comment by derekbruening** [comment]
add to whitelist

**Comment by derekbruening** [comment]
run arm tests

**Review by derekbruening — APPROVED** [review]
Thank you for the fix.

The commit title and description aren't following our conventions (https://dynamorio.org/page_code_reviews.html#sec_commit_messages).  I will fix on merge but keep in mind for future PR's.

**Comment by prasun3** [comment]
> 
> 
> Thank you for the fix.
> 
> The commit title and description aren't following our conventions (https://dynamorio.org/page_code_reviews.html#sec_commit_messages). I will fix on merge but keep in mind for future PR's.

I will keep this in mind for future changes.

**Pull request merged**
