### PR TITLE
i#5195: Upgrade to Windows 2019 for Github Actions

### PR DESCRIPTION
**Pull request by abhinav92003**
Upgrades (or rather attempts to upgrade) the Windows version in Github Actions config to windows-2019. This is required because windows-2016 will be removed on March 15 2022.

Issue: #5195

### CODE REVIEW

**Comment by derekbruening** [comment]
Note that we already have a builder-only (no tests) on windows-2019, thanks to PR #5274, so we know it builds with VS2019 on that platform.

**Comment by abhinav92003** [comment]
> Note that we already have a builder-only (no tests) on windows-2019, thanks to PR #5274, so we know it builds with VS2019 on that platform.

Yes, I think I was missing some updates to the environment setup which caused the failing builds.

**Comment by abhinav92003** [comment]
There are 4 new test failures (assuming the same tests in different suites fail for the same reason):

32-bit:
```
====> FAILURE in debug-internal-32 <====
debug-internal-32: 237 tests passed, **** 8 tests failed, but ignoring 5 for i#2145: ****
	(ignore: i#2145) 	code_api|win32.hookerfirst 
	code_api|security-win32.except-execution 
	(ignore: i#2145) 	code_api|client.drx-test 
	code_api|client.tls 
	code_api|client.drsyms-test 
	(ignore: i#2145) 	code_api|client.pcache-use 
	(ignore: i#2145) 	code_api|api.startstop 
	(ignore: i#2145) 	code_api|api.detach 
```

64-bit:
```
debug-internal-64: 253 tests passed, **** 16 tests failed, but ignoring 13 for i#2145: ****
	(ignore: i#2145) 	code_api|common.nativeexec 
	(ignore: i#2145) 	code_api|win32.mixedmode_late 
	(ignore: i#2145) 	code_api|win32.mixedmode 
	(ignore: i#2145) 	code_api|win32.x86_to_x64 
	(ignore: i#2145) 	code_api|win32.x86_to_x64_ibl_opt 
	(ignore: i#2145) 	code_api|client.cleancall 
	(ignore: i#2145) 	code_api|client.loader 
	(ignore: i#2145) 	code_api|client.drmgr-test 
	(ignore: i#2145) 	code_api|client.drx-test 
	code_api|client.tls 
	code_api|client.drsyms-testgcc 
	(ignore: i#2145) 	code_api|client.drutil-test 
	code_api|client.drsyms-test 
	(ignore: i#2145) 	code_api|client.pcache-use 
	(ignore: i#2145) 	code_api|client.drwrap-test-detach 
	(ignore: i#2145) 	code_api|api.detach 
```

**Comment by abhinav92003** [comment]
#5424 completed this.

**Pull request closed without merging**
