### PR TITLE
Use std namespace qualifier for strings.

### PR DESCRIPTION
**Pull request by snehasish**
Use std namespace qualifier for strings so that they don't cause conflicts with google internal libraries.

### CODE REVIEW

**Comment by Carrotman42** [comment]
LGTM

**Comment by Carrotman42** [comment]
Approve!

**Comment by Carrotman42** [comment]
Figured it out :)

**Comment by snehasish** [comment]
Looks like the failing travis build is due to #2941. Rerunning to deflake.

**Pull request merged**
