### PR TITLE
i#4083 func view: Add read-without-mapping module_mapper_t interface

### PR DESCRIPTION
**Pull request by derekbruening**
Adds a new module_mapper_t interface read_without_mapping_modules()
for parsing the module bounds without mapping the modules into memory.

Adds find_trace_module() for querying which module a given trace PC
came from, for use cases such as the function trace viewing tool (to
identify which symbol came from which library) where the data inside
the modules is not needed.

Adds a test.

Issue: #4083

### CODE REVIEW

**Comment by derekbruening** [comment]
So my plan was to use this to qualify traced symbols with the library name, which seems very useful.  I would want to know whether I had traced libc!malloc or libfoo!malloc.  However, I did not plan ahead very well, and found out after implementing its use in the new viewing tool that reconstructing the library after the fact for the return point is not as simple as looking at the prior PC:

```
Function 'libstdc++.so.6.0.28!__GI___libc_malloc' (id=8)
       22 calls
        0 returns
Function 'libc-2.29.so!__GI___libc_malloc' (id=8)
        2 calls
       25 returns
Function 'ld-2.29.so!__GI___libc_malloc' (id=8)
        1 calls
        0 returns
```

So the callee wrap point has the instruction PC for the target, but the call site return point has the caller, resulting in mis-attributed functions for the pre point vs the post point.  Just for statistics here we could just not track returns, and the full trace view still looks good:

```
0x7f9461807d56 => 8 ld-2.29.so!__GI___libc_malloc(0x11c00)
    0x7f9461807d56 => 8 libc-2.29.so!__GI___libc_malloc(0x11c00) => 0x7f945e0e92a0
=> 0x7f945e0e92a0
0x7f946180b745 => 8 libstdc++.so.6.0.28!__GI___libc_malloc(0x20) => 0x7f945e0faeb0
0x7f9461616d8c => 8 libc-2.29.so!__GI___libc_malloc(0x400) => 0x7f945e0faee0
0x7f946180b745 => 8 libstdc++.so.6.0.28!__GI___libc_malloc(0x48) => 0x7f945e0fb2f0
0x7f946180b745 => 8 libstdc++.so.6.0.28!__GI___libc_malloc(0x1c) => 0x7f945e0fb340
```

But a more sophisticated analysis that wants to split by 'lib!func' and needs to correlate the func args with the return value is going to have to go keep a stack of calls to match things up, which sounds like a pain.

Maybe instead the better approach is to only support 'lib!func' up front at tracing time by taking in a 'lib!func' string there with its own id, and leave the viewing tool just tracking id's and the corresponding names from the tracing itself?  In that case I would not need this PR.  Maybe it would be useful for something else; or maybe it's better to just throw it out.

**Comment by derekbruening** [comment]
OTOH some uses cases might want to trace '*!func' and split them up by library during analysis.  But it should be easier for the tracer to split them up: give each a different id when it asks to wrap them.  So maybe the -record_function interface should *not* take in an id, since we're now recording the strings in a file (decisions after offline discussion last week)?  And the tracer should just assign an atomically-incremented counter as the id.

**Comment by s-kanev** [comment]
Agree that specifying 'lib!func' upfront up front sounds like the better way to go in general.

Just bear in mind for our internal case (at least the most common one, by a lot), the allocator will be linked in statically and called directly in the main module (and not a library). So, the discrepancy in that case shouldn't exist.

**Comment by derekbruening** [comment]
Abandoning this since there is no current use case.  It might be useful in the future but it's not that hard to re-write and that seems cleaner than trying to keep it around.

**Pull request closed without merging**
