### PR TITLE
i#4953: Upgrade CI config to use Ubuntu 20.04.

### PR DESCRIPTION
**Pull request by abhinav92003**
Upgrades various Github Actions CI config to use Ubuntu 20.04. This is required because Ubuntu 16.04 support
in Github Actions is going to be deprecated in Sept 2021.

Fixes: #4953

### CODE REVIEW

**Comment by abhinav92003** [comment]
x86-64 has two failures:
`code_api|tool.drcacheoff.rseq`: Missing "Trace invariant checks passed" in output

`code_api|tool.drcacheoff.snappy`: Just a missing comma it seems (`Hits:                           78,312`)

x86-32 however has a  long list of failures:
```
2021-06-30T16:41:12.4587441Z debug-internal-32: 293 tests passed, **** 62 tests failed, of which 4 were flaky, but ignoring 2 for i#2941: ****
2021-06-30T16:41:12.4588304Z 	code_api|common.decode 
2021-06-30T16:41:12.4589187Z 	(ignore: i#2941) 	code_api|common.decode-stress 
2021-06-30T16:41:12.4590097Z 	code_api|linux.fork-sleep 
2021-06-30T16:41:12.4590824Z 	code_api|linux.signal0000 
2021-06-30T16:41:12.4591445Z 	code_api|linux.signal0001 
2021-06-30T16:41:12.4592063Z 	code_api|linux.signal0010 
2021-06-30T16:41:12.4592651Z 	code_api|linux.signal0011 
2021-06-30T16:41:12.4593265Z 	code_api|linux.signal0100 
2021-06-30T16:41:12.4593868Z 	code_api|linux.signal0101 
2021-06-30T16:41:12.4594459Z 	code_api|linux.signal0110 
2021-06-30T16:41:12.4595064Z 	code_api|linux.signal0111 
2021-06-30T16:41:12.4595667Z 	code_api|linux.signal1000 
2021-06-30T16:41:12.4596256Z 	code_api|linux.signal1001 
2021-06-30T16:41:12.4596861Z 	code_api|linux.signal1010 
2021-06-30T16:41:12.4597478Z 	code_api|linux.signal1011 
2021-06-30T16:41:12.4598062Z 	code_api|linux.signal1100 
2021-06-30T16:41:12.4598663Z 	code_api|linux.signal1101 
2021-06-30T16:41:12.4599267Z 	code_api|linux.signal1110 
2021-06-30T16:41:12.4599979Z 	code_api|linux.signal1111 
2021-06-30T16:41:12.4600582Z 	code_api|linux.sigplain000 
2021-06-30T16:41:12.4601217Z 	code_api|linux.sigplain001 
2021-06-30T16:41:12.4601911Z 	code_api|linux.sigplain010 
2021-06-30T16:41:12.4602527Z 	code_api|linux.sigplain011 
2021-06-30T16:41:12.4603242Z 	code_api|linux.sigplain100 
2021-06-30T16:41:12.4603876Z 	code_api|linux.sigplain101 
2021-06-30T16:41:12.4604489Z 	code_api|linux.sigplain110 
2021-06-30T16:41:12.4605128Z 	code_api|linux.sigplain111 
2021-06-30T16:41:12.4605751Z 	code_api|linux.syscall_pwait 
2021-06-30T16:41:12.4606345Z 	code_api|linux.sigcontext 
2021-06-30T16:41:12.4606936Z 	code_api|linux.signal_race 
2021-06-30T16:41:12.4607483Z 	code_api|linux.alarm 
2021-06-30T16:41:12.4608335Z 	code_api|linux.bad-signal-stack 
2021-06-30T16:41:12.4608982Z 	code_api|linux.eintr 
2021-06-30T16:41:12.4609761Z 	code_api|linux.eintr-noinline 
2021-06-30T16:41:12.4610391Z 	code_api|linux.signest 
2021-06-30T16:41:12.4611023Z 	(ignore: i#2941) 	code_api|pthreads.ptsig 
2021-06-30T16:41:12.4611876Z 	code_api|linux.persist-use_FLAKY 
2021-06-30T16:41:12.4612517Z 	code_api|client.events 
2021-06-30T16:41:12.4613092Z 	code_api|client.events_cpp 
2021-06-30T16:41:12.4613672Z 	code_api|client.timer 
2021-06-30T16:41:12.4614230Z 	code_api|client.signal 
2021-06-30T16:41:12.4614843Z 	code_api|client.cleancallsig 
2021-06-30T16:41:12.4615496Z 	code_api|linux.sigsuspend 
2021-06-30T16:41:12.4616292Z 	code_api|client.pcache-use 
2021-06-30T16:41:12.4616893Z 	code_api|tool.drcov.fib 
2021-06-30T16:41:12.4617589Z 	code_api|tool.drcacheoff.burst_threads 
2021-06-30T16:41:12.4618438Z 	code_api|tool.drcacheoff.burst_threadfilter 
2021-06-30T16:41:12.4619338Z 	code_api|tool.drcacheoff.burst_threadL0filter 
2021-06-30T16:41:12.4620180Z 	code_api|tool.histogram.offline 
2021-06-30T16:41:12.4621188Z 	code_api|tool.drcpusim.cpuid-Klamath 
2021-06-30T16:41:12.4622280Z 	code_api|tool.drcpusim.cpuid-Deschutes 
2021-06-30T16:41:12.4623113Z 	code_api|api.detach_spawn_stress_FLAKY 
2021-06-30T16:41:12.4623738Z 	code_api|api.static_signal 
2021-06-30T16:41:12.4624264Z 	code_api|api.detach 
2021-06-30T16:41:12.4624872Z 	code_api|api.static_maps_mixup_novars_FLAKY 
2021-06-30T16:41:12.4625560Z 	code_api,opt_memory|client.events 
2021-06-30T16:41:12.4626218Z 	code_api,opt_speed|client.events 
2021-06-30T16:41:12.4626927Z 	code_api,thread_private|client.events 
2021-06-30T16:41:12.4627663Z 	code_api,disable_traces|client.events 
2021-06-30T16:41:12.4628484Z 	code_api,thread_private,disable_traces|client.events 
2021-06-30T16:41:12.4629308Z 	code_api,no_early_inject|client.events 
2021-06-30T16:41:12.4629991Z 	code_api|api.static_sideline_FLAKY 
```

clang-format diff has a weird failure:
```
CMake Error at /home/runner/work/dynamorio/dynamorio/suite/runsuite.cmake:239 (message):
  Error (1) running clang-format-diff: File "/usr/bin/clang-format-diff-6.0",
  line 94

      print 'Formatting', filename
            ^

  SyntaxError: Missing parentheses in call to 'print'.  Did you mean
  print('Formatting', filename)?
```
Am I looking at this wrong or did clang just found a formatting error in its own source? :D

**Comment by abhinav92003** [comment]
Or maybe it is a Python 2 vs 3 version discrepancy. The latter requires parenthesis for print.

**Comment by derekbruening** [comment]
> x86-64 has two failures:
> `code_api|tool.drcacheoff.rseq`: Missing "Trace invariant checks passed" in output

Is this the same as #4924 and maybe that's unrelated to aarch64?

**Comment by abhinav92003** [comment]
Also x86-64 debug build has the following:
```
====> FAILURE in debug-internal-64 <====
debug-internal-64: 375 tests passed, **** 6 tests failed, of which 2 were flaky, but ignoring 0 for i#2941: ****
	code_api|client.pcache-use 
	code_api|tool.drcov.fib 
	code_api|api.detach_state 
	code_api|api.static_maps_mixup_novars_FLAKY 
	code_api|tool.drcacheoff.snappy 
	code_api|api.static_sideline_FLAKY 
```

**Comment by derekbruening** [comment]
This can be closed as we are now on Ubuntu 20.04.

**Pull request closed without merging**
