### PR TITLE
i#3092 genapi: Refactor frontend, probe, and proc headers

### PR DESCRIPTION
**Pull request by derekbruening**
Cleans up dr_frontend.h and sets it up for direct copying.

Moves dr_probe.h content from hotpatch.c and globals_shared.h and
places it in a new file core/lib/probe_api.h for direct copying to
dr_probe.h.

Separates exported content from core/arch/proc.h into
core/arch/proc_api.h, which is exported directly as dr_proc.h.

Issue: #3092

### CODE REVIEW

**Comment by derekbruening** [comment]
Wow, the linker crashed on the jenkins machine:
```
collect2: fatal error: ld terminated with signal 11 [Segmentation fault]
compilation terminated.
suite/tests/CMakeFiles/api.static_startstop.dir/build.make:98: recipe for target 'suite/tests/bin/api.static_startstop' failed
```

**Comment by derekbruening** [comment]
run arm tests

**Comment by derekbruening** [comment]
The linker crash didn't repro on a 2nd run.  Hmm.

**Review by abhinav92003 — APPROVED** [review]

**Comment by derekbruening** [comment]
Filed #4836 so we have a record if it crashes again.

**Pull request merged**
