### PR TITLE
Enable more binutils tests that pass but were disabled.

### PR DESCRIPTION
**Pull request by khuey**
This time it's the 32 bit AVX-512 VNNI tests.

### CODE REVIEW

**Review by derekbruening — APPROVED** [review]

**Comment by derekbruening** [comment]
Actually if you could hold off merging let's put https://github.com/DynamoRIO/dynamorio/pull/7142 in first as the package I built from it is the current HEAD.

**Comment by derekbruening** [comment]
If you want to give LGTM to #7142 that will help

**Comment by derekbruening** [comment]
It's in: all good to go now.

**Comment by khuey** [comment]
I was too slow but it does LGTM.

**Pull request merged**
