### PR TITLE
i#1556: Mark JCC instructions as predicated

### PR DESCRIPTION
**Pull request by dvyukov**
Marks JCC instructions as predicated so that instr_is_predicated()
and instr_get_predicate() work for them.
This does not touch OP_jecxz because the predicate is not expressable
with the current predicates.

Issues: #1556

### CODE REVIEW

**Comment by dvyukov** [comment]
I need help decoding CI failures. E.g. the decode test:
```
     Start  16: code_api|common.decode
16: Test command: D:\a\dynamorio\dynamorio\build_debug-internal-64\bin64\drrun.exe "-s" "90" "-quiet" "-debug" "-use_dll" "D:/a/dynamorio/dynamorio/build_debug-internal-64/lib64/debug/dynamorio.dll" "-exit0" "-stderr_mask" "0xC" "-msgbox_mask" "0" "-dumpcore_mask" "0x7d" "-staged" "-code_api" "--" "D:/a/dynamorio/dynamorio/build_debug-internal-64/suite/tests/bin/common.decode.exe"
16: Test timeout computed to be: 600
16: <Application D:\a\dynamorio\dynamorio\build_debug-internal-64\suite\tests\bin\common.decode.exe (3904).  Internal Error: DynamoRIO debug check failure: D:\a\dynamorio\dynamorio\core\arch\x86\emit_utils.c:181 (instr_is_cti(inst) && !instr_is_cti_short(inst) && !TESTANY(~(PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN), instr_get_prefixes(inst))) || instr_is_cti_short_rewrite(inst, NULL)
16: (Error occurred @411 frags in tid 748)
16: version 8.0.18966, custom build
16: -no_dynamic_options -code_api -probe_api -dumpcore_mask 125 -stderr_mask 12 -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -no_inline_ignored_syscalls -staged -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
16: 0x00007ffcaa8db830 0x001dfcdc00000000
16: D:\a\dynamorio\dynamorio\build_debug-internal-64\lib64\debug\dynamorio.dll=0x0000000015000000>
 16/266 Test  #16: code_api|common.decode .......................................***Failed  Required regular expression not found. Regex=[^(<Application .*common\.decode.*AVX-512 was detected at PC 0x[0-9a-f]+. AVX-512 is not fully supported yet.>
```
https://github.com/DynamoRIO/dynamorio/runs/4422026902?check_suite_focus=true
https://github.com/DynamoRIO/dynamorio/runs/4422037581?check_suite_focus=true

I don't understand what's failing here.

**Comment by derekbruening** [comment]
Looks like this check, which is trying to exclude the PREFIX_ADDR flag in particular I think, needs to be updated to allow the pred bits at the top of instr_t.prefixes:
```C
!TESTANY(~(PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN), instr_get_prefixes(inst))
```

**Comment by dvyukov** [comment]
> Looks like this check, which is trying to exclude the PREFIX_ADDR flag in particular I think, needs to be updated to allow the pred bits at the top of instr_t.prefixes:
> 
> ```c
> !TESTANY(~(PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN), instr_get_prefixes(inst))
> ```

Looking into this.
Meanwhile, how can I run relevant tests locally?
I've tried:
```
$ ninja help | egrep "test|check"
libstl_test.so: phony
stl_test: phony
```
but these targets don't run any tests.

**Comment by dvyukov** [comment]
I did RTFM (https://dynamorio.org/page_test_suite.html) but `ninja test` hangs for me here:

```
Received 5 'define memory' requests for a total of 3024 bytes\.
$
]  0.01 sec
        Start 160: code_api|client.vg-annot-opt.full-decode
160/379 Test #160: code_api|client.vg-annot-opt.full-decode .....................   Passed    0.04 sec
        Start 161: code_api|client.vg-annot-opt.full-decode.tiny-bb
161/379 Test #161: code_api|client.vg-annot-opt.full-decode.tiny-bb .............   Passed    0.04 sec
        Start 162: code_api|client.vg-annot-opt.bb-truncate
162/379 Test #162: code_api|client.vg-annot-opt.bb-truncate .....................   Passed    0.06 sec
        Start 163: code_api|client.attach_test
```

**Comment by dvyukov** [comment]
> ```c
> !TESTANY(~(PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN), instr_get_prefixes(inst))
> ```

What exactly is this line?
I on HEAD 5424c6fb76aba162064368fda12cbab9bba5bfb2 but don't see any such line:

```
$ git grep "PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN"
core/arch/x86/emit_utils.c:            !TESTANY(~(PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN),
core/arch/x86/mangle.c:            if (TESTANY(~(PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN), prefixes)) {
core/arch/x86/mangle.c:                prefixes &= (PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN);
core/ir/x86/encode.c:            !TESTANY(~(PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN), instr->prefixes),
core/ir/x86/encode.c:        if (!TESTANY(~(PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN), instr->prefixes)) {
```

**Comment by dvyukov** [comment]
I am somewhat puzzled as to how to interpret test result.
With my change I got a number tests failing:
```
	 11 - linux.execve32 (Failed)
	 12 - linux.execve64 (Failed)
	 13 - code_api|common.broadfun (Failed)
	 14 - code_api|common.fib (Failed)
	 15 - code_api|common.decode-bad (Failed)
	 16 - code_api|common.decode (Failed)
	 17 - code_api|common.decode-stress (Failed)
	 18 - code_api|common.eflags (Failed)
	 19 - code_api|common.floatpc (Failed)
	 20 - code_api|common.floatpc_xl8all (Failed)
	 21 - code_api|common.getretaddr (Failed)
	 22 - code_api|common.nativeexec (Failed)
	 23 - code_api|common.nativeexec_retakeover (Failed)
	 24 - code_api|common.nativeexec_exe (Failed)
	 25 - code_api|common.nativeexec_bindnow (Failed)
	 29 - code_api|common.segfault (Failed)
	 30 - code_api|client.memval-test (Failed)
	 31 - code_api|linux.clone (Failed)
	 32 - code_api|linux.clone-pie (Failed)
	 33 - code_api|linux.execve-null (Failed)
	 34 - code_api|linux.child-blacklist (Failed)
	 35 - code_api|linux.child-whitelist (Failed)
	 36 - code_api|linux.execve-rec (Failed)
	 37 - code_api|linux.exit (Failed)
	 38 - code_api|linux.fork (Failed)
	 39 - code_api|linux.fork-sleep (Failed)
	 40 - code_api|linux.fork-MSR (Failed)
	 41 - code_api|linux.infinite (Failed)
	 42 - code_api|linux.longjmp (Failed)
	 43 - code_api|linux.prctl (Failed)
	 44 - code_api|linux.mmap (Failed)
	 45 - code_api|linux.zero-length-mem-ranges (Failed)
	 46 - code_api|linux.signal0000 (Failed)
	 47 - code_api|linux.signal0001 (Failed)
	 48 - code_api|linux.signal0010 (Failed)
	 49 - code_api|linux.signal0011 (Failed)
	 50 - code_api|linux.signal0100 (Failed)
	 51 - code_api|linux.signal0101 (Failed)
	 52 - code_api|linux.signal0110 (Failed)
	 53 - code_api|linux.signal0111 (Failed)
	 54 - code_api|linux.signal1000 (Failed)
	 55 - code_api|linux.signal1001 (Failed)
	 56 - code_api|linux.signal1010 (Failed)
	 57 - code_api|linux.signal1011 (Failed)
	 58 - code_api|linux.signal1100 (Failed)
	 59 - code_api|linux.signal1101 (Failed)
	 60 - code_api|linux.signal1110 (Failed)
	 61 - code_api|linux.signal1111 (Failed)
	 62 - code_api|linux.sigplain000 (Failed)
	 63 - code_api|linux.sigplain001 (Failed)
	 64 - code_api|linux.sigplain010 (Failed)
	 65 - code_api|linux.sigplain011 (Failed)
	 66 - code_api|linux.sigplain100 (Failed)
	 67 - code_api|linux.sigplain101 (Failed)
	 68 - code_api|linux.sigplain110 (Failed)
	 69 - code_api|linux.sigplain111 (Failed)
	 70 - code_api|linux.sigaction (Failed)
	 71 - code_api|linux.syscall_pwait (Failed)
	 72 - code_api|linux.sigaction_nosignals (Failed)
	 73 - code_api|linux.sigcontext (Failed)
	 74 - code_api|linux.thread (Failed)
	 75 - code_api|linux.threadexit (Failed)
	 76 - code_api|linux.threadexit2 (Failed)
	 77 - code_api|linux.signalfd (Failed)
	 78 - code_api|linux.alarm (Failed)
	 79 - code_api|linux.signal_race (Failed)
	 80 - code_api|linux.signal_racesys (Failed)
	 81 - code_api|linux.bad-signal-stack (Failed)
	 82 - code_api|linux.eintr (Failed)
	 83 - code_api|linux.eintr-noinline (Failed)
	 84 - code_api|linux.sigsuspend (Failed)
	 85 - code_api|linux.signest (Failed)
	 86 - code_api|linux.mangle_asynch (Failed)
	 87 - code_api|linux.app_tls (Failed)
	 88 - code_api|linux.readlink (Failed)
	 89 - code_api|linux.fib-conflict (Failed)
	 90 - code_api|linux.fib-conflict-early (Failed)
	 91 - code_api|linux.fib-static (Failed)
	 92 - code_api|linux.fib-pie (Failed)
	 93 - code_api|linux.vfork (Failed)
	 94 - code_api|linux.thread-reset (Failed)
	 95 - code_api|linux.clone-reset (Failed)
	 96 - code_api|pthreads.pthreads (Failed)
	 97 - code_api|pthreads.pthreads_exit (Failed)
	 98 - code_api|pthreads.ptsig (Failed)
	 99 - code_api|pthreads.pthreads_fork_FLAKY (Failed)
	100 - code_api|security-linux.trampoline (Failed)
	101 - code_api|linux.reset (Failed)
	102 - code_api|linux.rseq (Failed)
	103 - code_api|linux.rseq_table (Failed)
	104 - code_api|linux.rseq_noarray (Failed)
	105 - code_api|linux.rseq_disable (Failed)
	106 - code_api|security-common.codemod (Failed)
	107 - code_api|security-common.decode-bad-stack_FLAKY (Failed)
	108 - code_api|security-common.retexisting (Failed)
	109 - code_api|security-common.ret_noncall_trace (Failed)
	110 - code_api|security-common.retnonexisting (Failed)
	111 - code_api|security-common.selfmod2 (Failed)
	112 - code_api|security-common.selfmod-big (Failed)
	113 - code_api|security-common.selfmod (Failed)
	114 - code_api|float_DR (Failed)
	115 - code_api|float_vmbase (Failed)
	116 - code_api|low4GB (Failed)
	117 - code_api|security-common.TestAllocWE (Failed)
	118 - code_api|security-common.TestMemProtChg_FLAKY (Failed)
	120 - code_api|client.int64_overrides (Failed)
	124 - code_api|client.modules (Failed)
	125 - code_api|client.alloc (Failed)
	135 - code_api|client.exception (Failed)
	136 - code_api|client.annotation-concurrency (Failed)
	142 - code_api|client.annotation-concurrency-opt (Failed)
	144 - code_api|client.annotation-detection (Failed)
	149 - code_api|client.annotation-detection-opt (Failed)
	150 - code_api|client.partial_module_map (Failed)
	152 - code_api|client.segfault (Failed)
	153 - code_api|client.execfault (Failed)
	154 - code_api|client.vg-annot (Failed)
	159 - code_api|client.vg-annot-opt (Failed)
	163 - code_api|client.attach_test (Subprocess killed)
	164 - code_api|client.events (Failed)
	165 - code_api|client.events_cpp (Failed)
	166 - code_api|client.nudge_test (Failed)
	173 - code_api|client.emulation_api_simple (Failed)
	174 - code_api|client.file_io (Failed)
	176 - code_api|client.strace (Failed)
	178 - code_api|client.dr_options (Failed)
	179 - code_api|client.unregister (Failed)
	183 - code_api|client.large_options (Failed)
	184 - code_api|client.blackbox (Failed)
	185 - code_api|client.option_parse (Failed)
	186 - code_api|client.reg_size_test (Failed)
	187 - code_api|client.thread_exit_xl8 (Failed)
	189 - code_api|client.drcontainers-test (Failed)
	195 - code_api|client.process-id (Failed)
	210 - code_api|client.drmodtrack-test (Failed)
	215 - code_api|client.app_args (Failed)
	217 - code_api|client.destructor (Failed)
	219 - code_api|sample.bbcount (Failed)
	220 - code_api|sample.bbsize (Failed)
	221 - code_api|sample.div (Failed)
	222 - code_api|sample.empty (Failed)
	223 - code_api|sample.memtrace_simple (Failed)
	225 - code_api|sample.memval_simple (Failed)
	226 - code_api|sample.memval_simple_scattergather (Failed)
	227 - code_api|sample.instrace_simple (Failed)
	228 - code_api|sample.opcode_count (Failed)
	229 - code_api|sample.cbr (Failed)
	230 - code_api|sample.countcalls (Failed)
	231 - code_api|sample.inc2add (Failed)
	232 - code_api|sample.memtrace_x86_binary (Failed)
	233 - code_api|sample.memtrace_x86_text (Failed)
	234 - code_api|sample.instrace_x86_binary (Failed)
	235 - code_api|sample.instrace_x86_text (Failed)
	237 - code_api|sample.ssljack (Failed)
	238 - code_api|sample.modxfer (Failed)
	239 - code_api|sample.modxfer_app2lib (Failed)
	240 - code_api|sample.instrcalls (Failed)
	241 - code_api|sample.cbrtrace (Failed)
	242 - code_api|sample.hot_bbcount (Failed)
	243 - code_api|sample.wrap (Failed)
	244 - code_api|sample.signal (Failed)
	245 - code_api|sample.syscall (Failed)
	247 - code_api|sample.inline (Failed)
	248 - code_api|sample.inscount (Failed)
	249 - code_api|sample.inscount.cleancall (Failed)
	250 - code_api|sample.inscount.prof-pcs.cleancall (Failed)
	251 - code_api|sample.opcodes (Failed)
	252 - code_api|sample.stl_test (Failed)
	329 - code_api|client.float_DR (Failed)
	330 - code_api|client.float_vmbase (Failed)
	331 - code_api|client.float_vmbase_PIE (Failed)
	345 - code_api|api.detach_spawn (Failed)
	346 - code_api|api.detach_spawn_stress_FLAKY (Failed)
	351 - code_api|api.static_noclient (Failed)
	355 - code_api|api.static_signal (Failed)
	357 - code_api|api.static_sideline_FLAKY (Failed)
	360 - code_api|api.static_maps_mixup_novars_FLAKY (Failed)
	361 - code_api|api.thread_churn (Failed)
	366 - code_api|api.rseq (Failed)
	367 - code_api,opt_memory|client.events (Failed)
	368 - code_api,opt_speed|client.events (Failed)
	369 - code_api,thread_private|client.events (Failed)
	372 - code_api,no_early_inject|client.events (Failed)
	373 - code_api,satisfy_w_xor_x|linux.fork (Failed)
	374 - code_api,satisfy_w_xor_x|linux.signal_racesys (Failed)
	375 - code_api,satisfy_w_xor_x|linux.vfork (Failed)
	376 - code_api,satisfy_w_xor_x|security-common.selfmod2 (Failed)
```


But lots of tests failed on the current head as well:
```
The following tests FAILED:
	 11 - linux.execve32 (Failed)
	 12 - linux.execve64 (Failed)
	 84 - code_api|linux.sigsuspend (Failed)
	125 - code_api|client.alloc (Failed)
	163 - code_api|client.attach_test (Subprocess killed)
	173 - code_api|client.emulation_api_simple (Failed)
	219 - code_api|sample.bbcount (Failed)
	220 - code_api|sample.bbsize (Failed)
	221 - code_api|sample.div (Failed)
	223 - code_api|sample.memtrace_simple (Failed)
	225 - code_api|sample.memval_simple (Failed)
	226 - code_api|sample.memval_simple_scattergather (Failed)
	227 - code_api|sample.instrace_simple (Failed)
	228 - code_api|sample.opcode_count (Failed)
	229 - code_api|sample.cbr (Failed)
	230 - code_api|sample.countcalls (Failed)
	231 - code_api|sample.inc2add (Failed)
	232 - code_api|sample.memtrace_x86_binary (Failed)
	233 - code_api|sample.memtrace_x86_text (Failed)
	234 - code_api|sample.instrace_x86_binary (Failed)
	235 - code_api|sample.instrace_x86_text (Failed)
	237 - code_api|sample.ssljack (Failed)
	238 - code_api|sample.modxfer (Failed)
	239 - code_api|sample.modxfer_app2lib (Failed)
	240 - code_api|sample.instrcalls (Failed)
	241 - code_api|sample.cbrtrace (Failed)
	242 - code_api|sample.hot_bbcount (Failed)
	243 - code_api|sample.wrap (Failed)
	244 - code_api|sample.signal (Failed)
	245 - code_api|sample.syscall (Failed)
	247 - code_api|sample.inline (Failed)
	248 - code_api|sample.inscount (Failed)
	249 - code_api|sample.inscount.cleancall (Failed)
	250 - code_api|sample.inscount.prof-pcs.cleancall (Failed)
	251 - code_api|sample.opcodes (Failed)
	252 - code_api|sample.stl_test (Failed)
	355 - code_api|api.static_signal (Failed)
	357 - code_api|api.static_sideline_FLAKY (Failed)
	360 - code_api|api.static_maps_mixup_novars_FLAKY (Failed)
	366 - code_api|api.rseq (Failed)
```

Looking at one random test that failed only with my change, I am not sure how it's related:
```
 46/379 Test  #46: code_api|linux.signal0000 ....................................***Failed  Required regular expression not found. Regex=[^Sending SIGUSR2
Sending SIGUSR1
in signal handler
Got SIGUSR1
Sending SIGRTMAX
in signal handler
Got SIGRTMAX
Generating SIGSEGV
in signal handler
Got SIGSEGV
250006\.749760
$
```

**Comment by derekbruening** [comment]
> Meanwhile, how can I run relevant tests locally?

`ctest -V -R common.decode\$`

**Comment by derekbruening** [comment]
> > ```c
> > !TESTANY(~(PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN), instr_get_prefixes(inst))
> > ```
> 
> What exactly is this line? I on HEAD [5424c6f](https://github.com/DynamoRIO/dynamorio/commit/5424c6fb76aba162064368fda12cbab9bba5bfb2) but don't see any such line:

Maybe not pasted verbatim?  The assert gives you the line:

```
Internal Error: DynamoRIO debug check failure: D:\a\dynamorio\dynamorio\core\arch\x86\emit_utils.c:181
```

**Comment by dvyukov** [comment]
I've fixed the decode test failures. PTAL.
Most CI steps passed now, only `vs2017-32` failed. Can it be unrelated to my change maybe? 🤞

**Comment by derekbruening** [comment]
run arm tests

**Comment by derekbruening** [comment]
Unfortunately on re-run the win32 failure is still there, and that is not any known flaky test AFAIK:
```
79: <Application D:\a\dynamorio\dynamorio\build_debug-internal-32\suite\tests\bin\win32.dotnet.exe (4552).  Internal Error: DynamoRIO debug check failure: D:\a\dynamorio\dynamorio\core\emit.c:219 !PAD_FRAGMENT_JMPS(f->flags)
```

Such an assert can be related to prefixes on jumps as in #1988 so it does not seem inconceivable that it is caused by this if it somehow affects actual prefix bytes.

**Comment by dvyukov** [comment]
I need to learn how to grep logs for assert failures.

The Win32 failure is fixed. PTAL.

**Comment by derekbruening** [comment]
run arm tests

**Review by derekbruening — APPROVED** [review]
Thank you for submitting a PR and working through test issues to get it green.

It could be nice to add a simple sanity test that conditional branches are predicated (maybe to suite/tests/api/ir_x86.c)?

Also, I noticed force-pushes: for future PR's please avoid force-pushes on shared branches as it ruins review comment histories and blocks reviewers from looking only at new changes (xref https://dynamorio.org/page_code_reviews.html#sec_code_review_non_member,  https://dynamorio.org/page_code_reviews.html#autotoc_md114).  The final squash-and-merge will clean up the PR into a single commit.

**Comment by dvyukov** [comment]
> It could be nice to add a simple sanity test that conditional branches are predicated (maybe to suite/tests/api/ir_x86.c)?

Done. PTAL.

> Also, I noticed force-pushes: 

Oh, ok, the test is added as a separate commit.

The fix for the previous failure was to NOT add `PREFIX_PRED_MASK` in these checks:

```
void
mangle_exit_cti_prefixes(dcontext_t *dcontext, instr_t *instr)
{
...
        if (instr_is_cbr(instr)) {
            if (TESTANY(~(PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN), prefixes)) {
                remove = true;
                prefixes &= (PREFIX_JCC_TAKEN | PREFIX_JCC_NOT_TAKEN);
            }
```

**Comment by derekbruening** [comment]
run arm tests

**Review by derekbruening — APPROVED** [review]
Thanks for adding the test.  Should be good to merge; trying to trigger arm tests first.

**Comment by dvyukov** [comment]
Thanks for bearing with me!

**Pull request merged**
