### PR TITLE
Avoid failing in syscall_mix for traces without syscall markers

### PR DESCRIPTION
**Pull request by abhinav92003**
Removes the check for trace file type that fails for older traces that do not have the syscall marker. It is better to simply report zero counts than to fail with a fatal error.

### CODE REVIEW

**Review by derekbruening — APPROVED** [review]

**Comment by abhinav92003** [comment]
x86-32-ubuntu22 failure is #6416

**Comment by abhinav92003** [comment]
x86-64 api.rseq failure is #6185

**Comment by abhinav92003** [comment]
x86-32 bit failures are #6417.

**Comment by abhinav92003** [comment]
I'm going to go ahead and merge this with admin privileges, so that we can unblock some dependent work. This PR is a very simple change and the failures are known issues: #6417 and #6416.

**Pull request merged**
