### PR TITLE
i#2626 AArch64 Decode: Missing misc SIMD instructions, part 1

### PR DESCRIPTION
**Pull request by MDevereau**
Add the following instructions to the codec:
- ABS (scalar, vector)
- ADDP (scalar)
- SMAXV
- SMINV
- ZIP1
- ZIP2

Issue #2626

### CODE REVIEW

**Comment by MDevereau** [comment]
run arm tests

**Comment by MDevereau** [comment]
run arm tests

**Comment by MDevereau** [comment]
run arm tests

**Comment by MDevereau** [comment]
run arm tests

**Review by AssadHashmi — APPROVED** [review]

**Comment by MDevereau** [comment]
run arm tests

**Comment by MDevereau** [comment]
run arm tests

**Comment by MDevereau** [comment]
run arm tests

**Pull request merged**
