### PR TITLE
Ensure NULL is pointer-sized

### PR DESCRIPTION
**Pull request by derekbruening**
Updates the NULL defines used in DR to be pointer-sized to avoid
potential issues such as in PR #3920.

### CODE REVIEW

**Comment by derekbruening** [comment]
Waffling over abandoning this PR or trying to fix these compiler complaints.  Strangely there are none for clang on Linux: only clang on Mac and VS.  Need to see the extent of the VS errors: if only a couple it may be worth working around them.

**Comment by hgreving2304** [comment]
> Waffling over abandoning this PR or trying to fix these compiler complaints. Strangely there are none for clang on Linux: only clang on Mac and VS. Need to see the extent of the VS errors: if only a couple it may be worth working around them.

For which compilers does #    ifndef NULL even apply? Definitely not on Linux?

**Comment by derekbruening** [comment]
> > Waffling over abandoning this PR or trying to fix these compiler complaints. Strangely there are none for clang on Linux: only clang on Mac and VS. Need to see the extent of the VS errors: if only a couple it may be worth working around them.
> 
> For which compilers does # ifndef NULL even apply? Definitely not on Linux?

It seems to apply for all of them, or all that I investigated: e.g., that ifndef is indeed entered on my Linux laptop and my Linux desktop.

**Comment by hgreving2304** [comment]
> > > Waffling over abandoning this PR or trying to fix these compiler complaints. Strangely there are none for clang on Linux: only clang on Mac and VS. Need to see the extent of the VS errors: if only a couple it may be worth working around them.
> > 
> > 
> > For which compilers does # ifndef NULL even apply? Definitely not on Linux?
> 
> It seems to apply for all of them, or all that I investigated: e.g., that ifndef is indeed entered on my Linux laptop and my Linux desktop.

I checked. NULL is a macro in stddef.h, so w/o including a standard header, our definition kicks in. (void*) is correct, apparently some toolchains define as 0L instead, but we shouldn't do 0L, as in ILP64 this is not guaranteed 64-bit. I think we should fix the warnings.

**Comment by derekbruening** [comment]
Filed #3930 to cover this work.

**Pull request merged**
