### PR TITLE
i#2990: translate si_addr if a PC

### LINKED ISSUE #2990: siginfo_t.si_addr not updated on SIGILL
Today DR is not updating siginfo_t fields when it delivers signals to the
app: but for SIGILL, si_addr (and si_addr_lsb) contains a code cache
address.

### PR DESCRIPTION
**Pull request by derekbruening**
Adds translation of siginfo_t.si_addr when it's a PC.
Adds a test.

Fixes #2990

### CODE REVIEW

**Comment by AssadHashmi** [comment]
Hi Derek, this change causes builds on RHEL 7.x to fail because si_addr_lsb is not a member of _sigfault:
```
        /* SIGILL, SIGFPE, SIGSEGV, SIGBUS.  */
        struct
          {
            void *si_addr;      /* Faulting insn/memory ref.  */
          } _sigfault;
```

**Comment by derekbruening** [comment]
OK, I see the same thing on Mac.  Will fix, probably by adding our own siginfo_t definition.

**Comment by derekbruening** [comment]
(Because siginfo_t deliberately has padding and new fields are added to the end, we want to compile w/ the latest and blindly write to new fields regardless of whether they are used by the underlying kernel)

**Comment by derekbruening** [comment]
PR #3019

**Comment by derekbruening** [comment]
@AssadHashmi -- I don't have RHEL 7.x handy but 776730e should fix the issue: confirmed on Android which also has an older siginfo_t.

**Pull request merged**
