### PR TITLE
i#1569 trace support for AArch64, part 1: cbr invertion for AArch64

### PR DESCRIPTION
**Pull request by Vincent-lau**
This patch added implementation for instr_invert_cbr() on AArch64 as well as
changing the implementation of instr_set_predicate by clearing the predicate
bits before setting them.

Issue: #1569

### CODE REVIEW

**Comment by Vincent-lau** [comment]
First commit of attempting to add trace support for AArch64. Many of the work here is based on the patch #2442 which is work done Kevin @egrimley, but the branch i1569-trace seems to be a bit outdated so I started working on a new branch. Let me know if it is necessary to work on the old branch.

**Comment by AssadHashmi** [comment]
add to whitelist

**Comment by Vincent-lau** [comment]
> add to whitelist

Sorry, what is the whitelist, and what do I need to add?

**Comment by AssadHashmi** [comment]
> > add to whitelist
> 
> Sorry, what is the whitelist, and what do I need to add?

That comment is special in that it's a command directed at the Jenkins test server used for AArch64 testing.
It tells Jenkins that you are a new contributor and to allow your patch to build and run the test suite.
I only have to do it once for a contributor's first PR. From now on all your pre-commits tests will trigger automatically.

**Review by AssadHashmi — APPROVED** [review]

**Comment by AssadHashmi** [comment]
If you haven't already had a look, please see https://dynamorio.org/page_code_reviews.html#sec_commit_messages for our commit message format.

**Comment by derekbruening** [comment]
> i#1569 trace support for AArch64, part 1: cbr invertion for AArch64

Spelling: s/invertion/inversion/

**Comment by derekbruening** [comment]
> i#2974 trace support for AArch64, part 2: implementation of the main … 

Please merge part 1 by itself and post part 2 in a separate PR.

**Comment by derekbruening** [comment]
Be sure to see https://dynamorio.org/page_code_reviews.html#autotoc_md117 on Merging into Master and Cleaning Up the Final Commit Message

**Review by derekbruening — CHANGES_REQUESTED** [review]
Just re-iterating as an official review request to revert part 2 here as it should be in a separate PR.

**Review by derekbruening — APPROVED** [review]

**Comment by derekbruening** [comment]
> I don't think I can do the merge (the squash and merge button is greyed out). Is it because I don't have merge privileges or something I have missed some step before merging?

See the message "This branch is out-of-date with the base branch".  Press the "Update branch" button.

**Pull request merged**
