### PR TITLE
i#4312: Detect generation-time and internal-script suite errors

### LINKED ISSUE #4312: config-time failure not reported as error by runsuite_wrapper
In a PR #4309 I broke the AArch64 build by forgetting to include a new
file.  But it was reported as green:

39.178.83.194:8080/job/DynamoRIO-AArch64-Precommit/1382/console

```
CMake Error: Cannot determine link language for target "drmemfuncs".
CMake Error in core/CMakeLists.txt:
  Exporting the target "drmemfuncs" is not allowed since its linker language
  cannot be determined
Command exited with the value: 1
Error(s) when configuring the project

CMake Error at /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/suite/runsuite_common_post.cmake:118 (file):
  file failed to open for reading (No such file or directory):

    /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/build/xml:results/___debug-internal-64___Experimental___XML___Build.xml
Call Stack (most recent call first):
  /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/suite/runsuite.cmake:545 (include)

CMake Error at /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/suite/runsuite_common_post.cmake:118 (file):
  file failed to open for reading (No such file or directory):

    /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/build/xml:results/___release-external-64___Experimental___XML___Build.xml
Call Stack (most recent call first):
  /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/suite/runsuite.cmake:545 (include)
```

So it did indeed fail. But the wrapper script fails to detect the
config-time failure as an overall error (too loose in ignoring cross-arch
build attempts in multi-build setup?) and it showed up green.  Xref test
failures not being reported on Mac: #4022, but I think that's completely
different.

### PR DESCRIPTION
**Pull request by derekbruening**
Adds two new checks for runsuite error detection:

1) Look for CMake 3.x failure to generate (separate from config: cause of
regression here)

Tested:
  ====> FAILURE in arm-debug-internal-64 <====
  arm-debug-internal-64: **** pre-build configure errors ****

2) Look for failure in runsuite scripts themselves.

Tested by removing fix for #1:
  ====> FAILURE in runsuite script itself <====
  CMake Error at suite/runsuite_common_post.cmake:119 (file):
    file failed to open for reading (No such file or directory):
      build_suite/xml:results/___arm-debug-internal-64___Experimental___XML___Build.xml
  Call Stack (most recent call first):
    suite/runsuite.cmake:545 (include)

Fixes #4312

### CODE REVIEW

**Comment by derekbruening** [comment]
Hmm the Travis failure is a real thing the new check found:

```
====> FAILURE in runsuite script itself <====
CMake Error at /home/travis/build/DynamoRIO/dynamorio/suite/runsuite_common_pre.cmake:665 (ctest_test):
  ctest_test called with unknown argument "orig_extra_ctest_args".
Call Stack (most recent call first):
  /home/travis/build/DynamoRIO/dynamorio/suite/runsuite_common_pre.cmake:749 (testbuild_ex)
  /home/travis/build/DynamoRIO/dynamorio/suite/runsuite.cmake:397 (testbuild)
```

Looks like a bug in runsuite.cmake where it doesn't de-ref a var properly.

**Comment by derekbruening** [comment]
Cool, it found another error:
```
CMake Error at core/CMakeLists.txt:93 (add_dependencies):
  The dependency target "api_headers" of target "drmemfuncs" does not exist.
```
Fixing now.

**Comment by derekbruening** [comment]
I'm going to put this in TBR.

**Comment by AssadHashmi** [comment]
Sorry, I didn't see this until today. I don't seem to be getting timely GitHub notifications.

**Pull request merged**
