### PR TITLE
i#1684 xarch-IR: Move IR files from core/arch to core/ir

### PR DESCRIPTION
**Pull request by derekbruening**
Moves all of the IR-related files (instruction generation, encoding,
decoding, disassembly, instructions, operands, instruction lists) from
core/arch to core/ir, mirroring the arch-specific subdirectories under
core/ir.  This is a code cleanup step toward properly isolating the
drdecode library, as well as moving us toward the ability to build for
a separate target architecture from the host architecture and
eventually perhaps building in multiple target architectures in the
same binary for decoding and IR manipulation.

Also renames mangle_utils.c to ir_utils.c to better fit its purpose
and location.

Issue: #1684

### CODE REVIEW

**Comment by johnfxgalea** [comment]
I'm wondering whether there is also any documentation that needs to be updated?

**Comment by johnfxgalea** [comment]
> I'm wondering whether there is also any documentation that needs to be updated?

Could be that there is none since these changes relate to internal code, but I'll do a quick grep just in case.

**Comment by derekbruening** [comment]
> > I'm wondering whether there is also any documentation that needs to be updated?
> 
> Could be that there is none since these changes relate to internal code, but I'll do a quick grep just in case.

Thanks.  I did do some grepping and updating comments in addition to code but I did not do exhaustive searches, nor did I look in the wiki.

**Comment by derekbruening** [comment]
The wiki just has `arch/` in ARM-Port.md, which contains historical design discussions and I'm inclined to leave it, and in JIT-Optimization.md which is a branch off an older version and so it should be left as well.

**Comment by derekbruening** [comment]
I'm not seeing anything in `api/`.  I don't recall any docs in general talking about internal source code layout.

**Comment by johnfxgalea** [comment]
When I did a grep, I found: 

```
./tools/x86opnums.pl:35:### enum in src/arch/*/opcode.h
./core/perscache.c:859:/* These decode-and-instr-using routines could go in arch/ as they assume that direct
./core/os_shared.h:1254:/* FIXME: if we add more opcodes maybe should be exported by arch/ */
./core/unix/os_exports.h:72: * Keep this consistent w/ the TLS_SEG_OPCODE define in arch/instr.h
```

**Comment by derekbruening** [comment]
Done:
+ ./tools/x86opnums.pl
+ ./core/os_shared.h
+ ./core/unix/os_exports.h:
+ ./core/vmareas.c
+ ./core/ir/decode.h

Unchanged:
+ ./core/perscache.c: that's DR-managed-execution-oriented code so it should remain arch/

**Comment by derekbruening** [comment]
Appveyor failures are burst_* which are known issues (unfortunately can't repro locally) and flaky: re-running to confirm, though last commit was just comments so almost no chance caused by this since 1st commit was green.

**Comment by derekbruening** [comment]
PTAL

**Pull request merged**
