### PR TITLE
i#1807: Add flaky long suite tests to ignore list

### PR DESCRIPTION
**Pull request by abhinav92003**
Adds some known flaky tests to ignore list to make master-merge CI green.

Issue: #1807

### CODE REVIEW

**Comment by abhinav92003** [comment]
There are some other tests, particularly the variants of `common.nativeexec_bindnow` and `common.decode-stress` that are seen to be failing, with slightly different options each time. Do we want to add those to ignore list already or wait for each different variant to fail multiple times?

**Comment by derekbruening** [comment]
I would add them all as it seems unlikely that the different options are a factor.  Maybe this PR could add a regex match or post-pipe-character match that ignores pre-pipe chars to make that easier to do with a single entry.

Maybe file a separate issue on the MAX_NATIVE_RETSTACK assert?

**Comment by abhinav92003** [comment]
> I would add them all as it seems unlikely that the different options are a factor. Maybe this PR could add a regex match or post-pipe-character match that ignores pre-pipe chars to make that easier to do with a single entry.

I added a quick change that does the latter. 
 
> Maybe file a separate issue on the MAX_NATIVE_RETSTACK assert?

#4868

**Comment by abhinav92003** [comment]
I experimented a bit with making it a perl regex based check, but adding new tests to the ignore list become tricky with many escaped and special chars in each entry. Perhaps not worth playing with regexps if the current solution is acceptable.

**Comment by abhinav92003** [comment]
PTAL. This is ready for review.

**Review by derekbruening — APPROVED** [review]

**Comment by abhinav92003** [comment]
`code_api|win32.hookerfirst` started failing in vs2017-32 suddenly 

Adding it to ignore list for now.

Created #4872

**Comment by derekbruening** [comment]
> `code_api|win32.hookerfirst` started failing in vs2017-32 suddenly
> 
> Adding it to ignore list for now.
> 
> Created #4872

Actually it's under #4870: showed up on some earlier PR's.  But it seems to suddenly be happening in every run: from some kind of VM update or sthg probably.

**Pull request merged**
