### PR TITLE
i#2121 date conversion: Add cast to avoid overflow.

### PR DESCRIPTION
**Pull request by egrimley**
Fixes breakage from 408e012.

### CODE REVIEW

**Comment by derekbruening** [comment]
Travis failed?

**Comment by egrimley** [comment]
> Travis failed?

Yes. It doesn't seem to have anything to do with the changes, but I
haven't seen that failure before, either.

**Comment by derekbruening** [comment]
Please file a new issue on any Travis failure that's not in the tracker, and mark it Hotlist-Travis.  Isn't this i#2066?  Did it not show up in an issue search?

```
debug-internal-64: 251 tests passed, **** 2 tests failed: ****
	code_api|linux.signal_race =>  Application /home/travis/build/DynamoRIO/dynamorio/build_debug-internal-64/suite/tests/bin/linux.signal_race (28967).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/link.c:1787 !TEST(FRAG_LINKED_OUTGOING, f-flags) 
	code_api|linux.signal_racesys =>  Application /home/travis/build/DynamoRIO/dynamorio/build_debug-internal-64/suite/tests/bin/linux.signal_racesys (28969).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/link.c:1787 !TEST(FRAG_LINKED_OUTGOING, f-flags) 
```

Just checking: you verified that this fixes the "25u" error?  Should be easy to repro in a release build with tests enabled.

**Comment by derekbruening** [comment]
In the interests of getting all those cdash builds fixed I went and checked and this does indeed fix the 25u error.

**Pull request merged**
