### PR TITLE
i#2626 AArch64 enc: Add FP data-processing instrs (1 source)

### PR DESCRIPTION
**Pull request by fhahn**
This patch adds support for the instructions in the Armv8-a
'Floating-point data-processing' encoding groups with 1 source.

Issue #2626

### CODE REVIEW

**Comment by derekbruening** [comment]
I'm on vacation and traveling for the next few days -- I will have some internet access but it may be best to ask a different reviewer in case I don't get to this until Monday

**Comment by fhahn** [comment]
Enjoy your vacation :) I'll check with either Edmund or Assad.

cc @andreipoe

**Comment by fhahn** [comment]
Travis failure is #2921

**Comment by fhahn** [comment]
Thanks Edmund!

**Pull request merged**
