### PR TITLE
i#4830: Work around GA CI VM 32-bit and clang-format toolchain regressions

### PR DESCRIPTION
**Pull request by derekbruening**
WIP: Try Ubuntu 20 for clang w/o the clang-9 env var;
Try Ubuntu 18 for x86 to see if toolchain is better w/o test failures

Issue: #4830

### CODE REVIEW

**Comment by derekbruening** [comment]
Exact same failures.  Prob fastest route is to install older gcc -- but it sure seems like we shouldn't have to do that: seems like their gcc-9 is messed up.

**Comment by derekbruening** [comment]
WIth "g++-8 g++-8-multlib" it's broken in another way:

```
   /usr/bin/c++ -m32  CMakeFiles/cmTC_f1708.dir/testCXXCompiler.cxx.o -o cmTC_f1708 
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.so when searching for -lstdc++
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.a when searching for -lstdc++
    /usr/bin/ld: cannot find -lstdc++
    collect2: error: ld returned 1 exit status
```

Grrr, this shouldn't be this hard.  It shouldn't have broken in the first place: we're fine with gcc 9.

**Comment by derekbruening** [comment]
So the suggested workaround from https://github.com/actions/virtual-environments/issues/2950#issuecomment-812105569 did work: a flaky test failed the 32-bit, and the wrong package name I think the clang-format.  So it seems the 32-bit-toolchain problem is from cmake 3.20.

**Comment by abhinav92003** [comment]
Thanks for the fix! 
Is there any way to subscribe to https://github.com/actions/virtual-environments/labels/Announcement? That should let us know of these required migrations early.

**Review by abhinav92003 — APPROVED** [review]

**Comment by derekbruening** [comment]
Looks like I still don't quite have the clang job right -- I think putting the env vars back will do it.

> Is there any way to subscribe to https://github.com/actions/virtual-environments/labels/Announcement? That should let us know of these required migrations early.

Not sure, but if I had seen the title of this one about gcc<9.0 I would have thought it would not affect us.  I wonder if the cmake 3.20 was a different announcement?  But I would have also assumed it wouldn't affect us.  Sill hard to believe cmake by itself would mess it up: wonder if it's a combination of cmake and sthg weird about these VM's.

**Pull request merged**
