### PR TITLE
i#5365 Update aarch64 workflow

### PR DESCRIPTION
**Pull request by spcaipers-arm**
Update ci-aarch64-native workflow with new runner on SVE hardware.
    
Adding a new self-hosted-runner for this pipeline to enhance the test
coverage. A list of unit tests which fail intermittently are added to
the ignore list ignore_failures_sve in runsuite_wrapper.pl.

Issue: #5365

### CODE REVIEW

**Comment by spcaipers-arm** [comment]
I changed the name of the CI workflow for better description with this change.
Probably we need to change the configuration to also add that to the required checks. 

It is expected `aarch64-native` and I changed to `ci-aarch64 / aarch64`

**Comment by abhinav92003** [comment]
Since there's no PR description (which is required as per https://dynamorio.org/page_code_reviews.html), it's hard for any reviewer to get context on what changes are being made and why.

**Comment by AssadHashmi** [comment]
x86 regressions due to known issues, see https://github.com/DynamoRIO/dynamorio/issues/6416 and https://github.com/DynamoRIO/dynamorio/issues/6417

**Comment by joshua-warburton** [comment]
Due to this pull request being sourced from a archived fork, I've opened pull request #6549 to replace it as otherwise it's impossible to update the branch

**Pull request closed without merging**
