### PR TITLE
i#1312 AVX-512 support: Fix VEX.L0/VEX.L1 in mask opcode encodings.

### PR DESCRIPTION
**Pull request by hgreving2304**
Fixes a bug where we didn't respect and check encodings rules for the VEX.L bit.

The VEX encoded AVX-512 instructions had not been ground-truth tested. The opcodes
have now been checked against llvm-mc and binutils/gas/objdump.

Issue: #1312

### CODE REVIEW

**Comment by derekbruening** [comment]
> The VEX encoded AVX-512 instructions had not been ground-truth tested. 

Because they were added early before those checks were done as part of the workflow?

Are there other instructions that have not been tested this way?

**Comment by hgreving2304** [comment]
> > The VEX encoded AVX-512 instructions had not been ground-truth tested.
> 
> Because they were added early before those checks were done as part of the workflow?
> 
> Are there other instructions that have not been tested this way?

All other instructions were ran against binutils/llvm-mc.

**Comment by Carrotman42** [comment]
Do we have automated checking against binutils/llvm-mc? Is the plan to regularly double-check in case one of those tools receives a bugfix for some bug that we also have?

**Comment by hgreving2304** [comment]
> Do we have automated checking against binutils/llvm-mc? Is the plan to regularly double-check in case one of those tools receives a bugfix for some bug that we also have?

This is https://github.com/DynamoRIO/dynamorio/issues/3638
I do have a script but due to various subtle syntax differences the issue hasn't been implemented yet (need some regular expression matches or alike). Wasn't the highest priority because once it's correctly in the encoding table it is unlikely to break easily. But yes, it's a TODO.

**Pull request merged**
